import { nowStamp } from "./clients";
import { readPersistedList } from "./seedOptions";
import { BULK_KEYWORD_SEEDS, BULK_URL_SEEDS } from "./seedsBulk";

export type SeedType = "URL" | "API" | "KEYWORD" | "PDP";
export type KeywordType = "BRANDED" | "CATEGORY";
export type SeedStatus = "Active" | "Inactive";

export const KEYWORD_TYPE_OPTIONS: KeywordType[] = ["BRANDED", "CATEGORY"];
export const SEED_STATUS_OPTIONS: SeedStatus[] = ["Active", "Inactive"];

// Field names d/store/cat/c/u are kept for backward compatibility (e.g. the
// Subscriptions seed dropdown reads `.d`). New type-aware fields are optional.
export type Seed = {
  id: string;
  d: string; // description
  store: string;
  cat: string; // category
  c: string; // created at
  u: string; // updated at
  type?: SeedType;
  status?: SeedStatus; // Active / Inactive
  isFromDiscovery?: boolean; // auto-generated by a PLP discovery seed
  discoveryKey?: string;
  pageType?: string;
  value?: string; // the URL / keyword / API origin, depending on type
  keywordType?: KeywordType; // BRANDED / CATEGORY — only for KEYWORD seeds
  brand?: string; // codification Brand name — only when keywordType === "BRANDED"
};

export const SEEDS_KEY = "seeds-api:seeds";

const BASE_SEEDS: Seed[] = [
  { id: "s1", d: "chocolate", store: "Walmart US", cat: "Pantry > Chocolate > Choco...", c: "2025-04-25, 11:11:33", u: "2025-04-25, 11:11:33", type: "KEYWORD", value: "chocolate", keywordType: "CATEGORY" },
  { id: "s2", d: "water", store: "Amazon US", cat: "Beverages > Waters > Other", c: "2026-06-08, 16:03:09", u: "2026-06-08, 16:03:09", type: "KEYWORD", value: "water", keywordType: "CATEGORY" },
  { id: "s3", d: "coffee", store: "Amazon US", cat: "Pantry > Coffee > Beans", c: "2026-01-30, 13:41:14", u: "2026-01-30, 13:41:14", type: "KEYWORD", value: "coffee", keywordType: "CATEGORY" },
  { id: "s4", d: "Milk", store: "Walmart US", cat: "Pantry > Coffee > Beans", c: "2026-01-30, 13:42:59", u: "2026-06-09, 10:00:00", type: "URL" },
  { id: "s5", d: "sample of keyword", store: "Walmart Mismo Dia MX", cat: "Beauty > Hair Care > Sham...", c: "2026-04-27, 12:43:10", u: "2026-04-27, 12:43:10", type: "KEYWORD", value: "sample of keyword", keywordType: "BRANDED", brand: "Sprite" },
];

// [description, keyword, keyword type, store, category]
const KEYWORD_ROWS: [string, string, KeywordType, string, string][] = [
  ["sprite sem açúcar", "sprite sem açúcar", "BRANDED", "iFood BR - Roldao", "Beverages > Soft Drinks > Soda"],
  ["helado brownie", "helado brownie", "CATEGORY", "El Corte Ingles Supermercado ES", "Fresh and Frozen > Other > Other"],
  ["canada dry", "canada dry", "BRANDED", "Uber Eats MX - Fresko", "Beverages > Beer > Beer"],
  ["del valle fizz naranja", "del valle fizz naranja", "CATEGORY", "Al Super APP MX", "Beverages > Juices > Soda"],
  ["cocacola", "cocacola", "BRANDED", "iFood BR - Barbosa", "Beverages > Soft Drinks > Soda"],
  ["laranja", "laranja", "CATEGORY", "Carrefour ES", "Beauty > Hair Care > Other"],
  ["pelo", "pelo", "CATEGORY", "Rappi App BR - Assaí Atacadista", "Beauty > Hair Care > Other"],
  ["ofertas del valle nectar", "ofertas del valle nectar", "CATEGORY", "Uber Eats MX - Costco", "Beverages > Juices > Other"],
  ["vitamin water", "vitamin water", "CATEGORY", "Rappi APP MX - Farmacias Guadalajara", "Beverages > Waters > Still Water"],
  ["energy drinks rockstar", "chocolate chip granola bar", "CATEGORY", "Uber Eats CA - Walmart", "Beverages > Soft Drinks > Energy Drinks"],
  ["zamek", "zamek", "CATEGORY", "Amazon PL", "Toys and Games > Building Toys > Building Blocks"],
  ["snacks papas fritas", "snacks papas fritas", "CATEGORY", "Jumbo AR", "Pantry > Snacks > Chips"],
  ["guarana tuchaua zero açúcar", "guarana tuchaua zero açúcar", "BRANDED", "Rappi App BR - Turbo", "Beverages > Soft Drinks > Soda"],
  ["cola light", "cola light", "CATEGORY", "Uber Eats App MX - Circle K", "Beverages > Soft Drinks > Soda"],
  ["snackmix", "snackmix", "CATEGORY", "Jumbo APP CL", "Pantry > Snacks > Other"],
  ["leche light leche", "leche light leche", "CATEGORY", "Rappi APP MX - Farmacias Guadalajara", "Fresh and Frozen > Milk > Other"],
  ["candelabros loewe", "candelabros loewe", "BRANDED", "Paco Perfumerias ES", "Beauty > Fragrances > Other"],
  ["fanta zero", "fanta zero", "CATEGORY", "Angeloni BR - Super", "Beverages > Soft Drinks > Soda"],
  ["caja de jugos del valle", "caja de jugos del valle", "BRANDED", "Rappi App MX - Calimax", "Beverages > Juices > Other"],
  ["haarmaske für trockenes haar", "haarmaske für trockenes haar", "CATEGORY", "Hagel Shop DE", "Beauty > Hair Care > Treatments"],
  ["coca-cola light mini", "coca-cola light mini", "CATEGORY", "Rappi APP MX - Circle K", "Beverages > Soft Drinks > Soda"],
  ["balayage shampoo", "balayage shampoo", "CATEGORY", "Sephora UK", "Beauty > Hair Care > Shampoo"],
  ["lata sprite", "lata sprite", "BRANDED", "Uber Eats MX - Soriana", "Beverages > Soft Drinks > Soda"],
  ["prebiotic soda", "diet pepsi 18 pack", "CATEGORY", "Uber Eats CA - 7 Eleven", "Beverages > Soft Drinks > Soda"],
  ["viajes en crucero", "viajes en crucero", "CATEGORY", "Uber Eats MX - 7 Eleven", "Other > Other > Other"],
  ["chocolate postres", "chocolate postres", "CATEGORY", "El Corte Ingles Mascotas ES", "Pantry > Chocolate > Other"],
  ["spindrift", "fruits", "CATEGORY", "Uber Eats APP CA - 7 Eleven", "Beverages > Waters > Sparkling Water"],
  ["mosh nutremas", "mosh nutremas", "CATEGORY", "Walmart GT", "Pantry > Cereals > Other"],
  ["soda antarctida", "soda antarctida", "BRANDED", "iFood BR - Carrefour", "Beverages > Soft Drinks > Soda"],
  ["lechitas", "lechitas", "CATEGORY", "Al Super MX", "Fresh and Frozen > Milk > Other"],
  ["protector solar facial", "protector solar facial", "CATEGORY", "Arenal ES", "Beauty > Personal Care > Sun Protection"],
  ["jugo", "jugo", "CATEGORY", "Uber Eats APP MX - HEB", "Beverages > Juices > Other"],
  ["kabsa mix", "kabsa mix", "CATEGORY", "Hunger Station APP SA", "Pantry > Other > Other"],
  ["mens fragrance set", "mens fragrance set", "CATEGORY", "Harrods UK", "Beauty > Fragrances > Other"],
  ["salsa soya", "salsa soya", "CATEGORY", "HEB MX", "Pantry > Condiments and Sauces > Sauces"],
  ["pienso atopic perros", "pienso atopic perros", "CATEGORY", "Tienda Animal ES", "Pets > Dog > Food"],
  ["diet soda", "diet soda", "CATEGORY", "Sams Club US", "Beverages > Soft Drinks > Soda"],
  ["saladitas", "saladitas", "BRANDED", "Rappi APP MX - 7 Eleven", "Pantry > Snacks > Chips"],
  ["limão", "limão", "BRANDED", "Pao de Acucar BR", "Beverages > Soft Drinks > Soda"],
  ["cerveza ambar", "cerveza ambar", "CATEGORY", "Soriana MX", "Beverages > Beer > Beer"],
  ["lomecan", "lomecan", "BRANDED", "Farmacia San Pablo MX", "Beauty > Intimate Care > Other"],
  ["fuze", "fuze", "BRANDED", "Rappi APP MX - Turbo", "Beverages > Ready-to-drink > Iced Tea"],
  ["fragancia de viaje para hombre", "fragancia de viaje para hombre", "CATEGORY", "Sephora ES", "Beauty > Fragrances > Other"],
  ["brettspiele", "brettspiele", "CATEGORY", "Rofu DE", "Toys and Games > Games and Puzzles > Board Games"],
  ["sabor", "sabor", "CATEGORY", "Bonpreu Esclat ES", "Pantry > Other > Other"],
  ["picnic", "picnic", "CATEGORY", "Uber Eats MX - Fresko", "DIY > Garden > Other"],
  ["mens cologne spray", "mens cologne spray", "CATEGORY", "Net A Porter APP UK", "Beauty > Fragrances > Other"],
  ["danone", "danone", "BRANDED", "Rappi APP MX - Turbo", "Fresh and Frozen > Fresh Food > Other"],
  ["laundry detergent", "laundry detergent", "CATEGORY", "Amazon US", "Home Care and Cleaning > Dish Detergent"],
  ["galleta mamut", "galleta mamut", "CATEGORY", "Walmart GT", "Pantry > Breakfast and Bakery > Biscuits and Cookies"],
  ["caja jugos del valle", "caja jugos del valle", "BRANDED", "Rappi App MX - Calimax", "Beverages > Juices > Other"],
  ["cepillos para el cabello", "cepillos para el cabello", "CATEGORY", "Alkosto CO", "Beauty > Hair Care > Other"],
  ["sidral mundet ciruela", "sidral mundet ciruela", "BRANDED", "Uber Eats MX - Sumesa", "Beverages > Soft Drinks > Soda"],
  ["nectar de manzana del valle", "nectar de manzana del valle", "BRANDED", "Uber Eats MX - Chedraui", "Beverages > Juices > Other"],
  ["ofertas del valle nectar", "ofertas del valle nectar", "BRANDED", "La Comer MX", "Beverages > Juices > Other"],
  ["leche de soja calcio", "leche de soja calcio", "CATEGORY", "Dia ES", "Fresh and Frozen > Milk > Plant-Based Milk"],
  ["del valle fizz naranja", "del valle fizz naranja", "BRANDED", "Walmart Mismo Dia MX", "Beverages > Juices > Other"],
  ["bocaditos", "bocaditos", "CATEGORY", "El Corte Ingles Mascotas ES", "Pantry > Other > Other"],
  ["lego marvel", "lego marvel", "BRANDED", "The Entertainer UK", "Toys and Games > Building Toys > Building Blocks"],
  ["powder foundation", "powder foundation", "CATEGORY", "Sainsburys UK", "Beauty > Other > Other"],
  ["running tips", "running tips", "CATEGORY", "Rappi APP MX - Soriana Hiper", "Other > Yoga and Sports > Other"],
  ["lego disney", "lego disney", "BRANDED", "Otto DE", "Toys and Games > Building Toys > Building Blocks"],
  ["agua sem gás", "água sem gás", "CATEGORY", "iFood BR - Extra", "Beverages > Waters > Still Water"],
  ["pienso humedo perros", "pienso humedo perros", "CATEGORY", "Glovo APP ES - Super Glovo", "Pets > Dog > Food"],
  ["frutas citricas", "frutas citricas", "CATEGORY", "Supermosso BR", "Fresh and Frozen > Milk > Other"],
  ["lechitas", "lechitas", "CATEGORY", "Rappi App MX - Calimax", "Fresh and Frozen > Milk > Other"],
  ["vermu blanco", "vermu blanco", "CATEGORY", "Amazon ES", "Beverages > Wine > Fortified Wine"],
  ["sheba", "sheba", "BRANDED", "Zooplus UK", "Pets > Cat > Food"],
  ["agua mineral", "agua mineral", "BRANDED", "Glovo APP ES - Carrefour", "Beverages > Waters > Still Water"],
  ["alpro natural con avena", "alpro natural con avena", "BRANDED", "Dia ES", "Fresh and Frozen > Yogurt > Plant-Based Yogurt"],
  ["cacao sin azucar", "cacao sin azucar (old)", "CATEGORY", "El Corte Ingles Supermercado ES", "Fresh and Frozen > Other > Other"],
  ["coca cola", "coca cola", "CATEGORY", "PedidosYa APP PE - Market", "Beverages > Soft Drinks > Soda"],
  ["del valle nectar durazno", "del valle nectar durazno", "BRANDED", "Uber Eats APP MX - La Comer", "Beverages > Juices > Other"],
  ["epura", "epura", "BRANDED", "Justo APP MX", "Beverages > Waters > Still Water"],
  ["automobili", "automobili", "CATEGORY", "Amazon IT", "Toys and Games > Other > Other"],
  ["gut health soda", "gut health soda", "CATEGORY", "Sams Club US", "Beverages > Soft Drinks > Soda"],
  ["avengers spielzeug", "avengers spielzeug", "CATEGORY", "Media Markt DE", "Toys and Games > Other > Other"],
  ["Kenzo intense", "Kenzo intense", "BRANDED", "Primor ES", "Beauty > Fragrances > Other"],
  ["caldo natural", "caldo natural", "CATEGORY", "Bonpreu Esclat ES", "Pantry > Soups > Other"],
  ["cacao soluble instantaneo", "cacao soluble instantaneo", "CATEGORY", "Alcampo ES", "Pantry > Breakfast and Bakery > Chocolate"],
  ["agua micelar", "agua micelar", "CATEGORY", "Falabella PE", "Beauty > Personal Care > Face Care"],
  ["pepperoni pizza", "pepperoni pizza", "CATEGORY", "Amazon US", "Fresh and Frozen > Pasta > Other"],
  ["batman", "batman", "BRANDED", "Emag RO", "Toys and Games > Action Figures and Playsets"],
  ["queso tarrina", "queso tarrina", "CATEGORY", "Amazon Fresh ES", "Fresh and Frozen > Cheese > Other"],
  ["torta de pierna", "torta de pierna", "CATEGORY", "Soriana APP MX", "Pantry > Breakfast and Bakery > Wraps"],
  ["ijsthee", "ijsthee", "CATEGORY", "Albert Heijn Web NL", "Beverages > Other > Other"],
  ["pienso gato esterilizado", "pienso gato esterilizado", "CATEGORY", "Amazon ES", "Pets > Cat > Food"],
  ["santa clara deslactosada light", "santa clara deslactosada light", "BRANDED", "Uber Eats MX - Costco", "Fresh and Frozen > Milk > Other"],
  ["mario", "mario", "BRANDED", "Takealot APP ZA", "Toys and Games > Other > Other"],
  ["fresca lata", "fresca lata", "CATEGORY", "Uber Eats MX - Soriana", "Beverages > Other > Other"],
  ["pastilla de caldo", "pastilla de caldo", "CATEGORY", "Drinx ES", "Pantry > Soups > Soup Broth"],
  ["santa clara chopeo", "santa clara chopeo", "BRANDED", "Uber Eats MX - Circle K", "Fresh and Frozen > Milk > Other"],
  ["olla arrocera", "olla arrocera", "CATEGORY", "Mercado Libre MX", "Home and Appliances > Small Appliances > Other"],
  ["agua sem gas", "agua sem gas", "CATEGORY", "Amazon App BR", "Beverages > Waters > Still Water"],
  ["leao", "leao", "BRANDED", "Arco Mix APP BR", "Beverages > Ready-to-drink > Iced Tea"],
  ["cerveza 25cl", "cerveza 25cl", "CATEGORY", "Alcampo ES", "Beverages > Beer > Beer"],
  ["avengers loksaker", "avengers loksaker", "BRANDED", "Toyspace SE", "Toys and Games > Other > Other"],
  ["natural trainer", "natural trainer", "BRANDED", "Amazon IT", "Pets > Dog > Food"],
  ["samochód policyjny", "samochód policyjny", "CATEGORY", "Empik PL", "Toys and Games > Action Figures and Playsets"],
  ["carro electrico", "carro electrico", "CATEGORY", "Mercado Libre MX", "Toys and Games > Youth Electronics > Remote Control"],
];

// A handful of BRANDED keyword rows get a real codification Brand assigned (by
// description) so the Seeds list / form show populated relationships; the rest
// stay unbonded ("—"), matching the production mix.
const BRAND_BY_DESC: Record<string, string> = {
  "sprite sem açúcar": "Sprite",
  "cocacola": "Coca-Cola",
  "lata sprite": "Sprite",
  "limão": "Fanta",
  "fuze": "Coca-Cola",
};

const KEYWORD_SEEDS: Seed[] = KEYWORD_ROWS.map(([d, keyword, keywordType, store, cat], i) => {
  const day = String((i % 28) + 1).padStart(2, "0");
  const min = String((i * 13) % 60).padStart(2, "0");
  const stamp = `2026-05-${day}, 09:${min}:00`;
  const brand = keywordType === "BRANDED" ? BRAND_BY_DESC[d] : undefined;
  return { id: `k${i + 1}`, d, store, cat, c: stamp, u: stamp, type: "KEYWORD", value: keyword, keywordType, ...(brand ? { brand } : {}), status: "Active" as SeedStatus };
});

// URL seeds — Amazon US. [description, url, pageType, category]
const URL_ROWS: [string, string, string, string][] = [
  ["Home > Grocery and gourmet food > Pantry staples", "https://www.amazon.com/?rh=n=18320331", "SUBCATEGORY", "Pantry > Condiments and Sauces > Oil"],
  ["Home > Grocery & Gourmet Food > Snacks & Sweets > Chocolate Candy", "https://www.amazon.com/?keywords=Candy+%26+Chocolate+Bars&rh=n", "SUBCATEGORY", "Pantry > Chocolate > Tablets"],
  ["Home > Beauty and personal care > Skin care > Body care > Body", "https://www.amazon.com/?rh=n=11060661", "SUBCATEGORY", "Beauty > Personal Care > Skin Care"],
  ["Home > Grocery and gourmet food > Pantry staples", "https://www.amazon.com/?rh=n=18787303011", "SUBCATEGORY", "Fresh and Frozen > Other > Other"],
  ["Home > Beauty & Personal Care > Skin Care Products", "https://www.amazon.com/?i=beauty&rh=n%3A3760911%2Cn%3A11060451", "CATEGORY", "Beauty > Personal Care > Skin Care"],
  ["Home > Beauty and personal care > Hair care > Hair loss > Hair regrowth", "https://www.amazon.com/?rh=n=18262642011", "SUBCATEGORY", "Beauty > Hair Care > Conditioner"],
  ["Home > Grocery & Gourmet Food > Snacks & Sweets > Breakfast & Cereal", "https://www.amazon.com/?keywords=Breakfast+%26+Cereal+Bars&i=grocery", "SUBCATEGORY", "Pantry > Cereals > Cereal Bars"],
  ["Home > Grocery & Gourmet Food > Snacks & Sweets > Breakfast & Cereal", "https://www.amazon.com/?keywords=Breakfast+%26+Cereal+Bars&rh=n", "SUBCATEGORY", "Pantry > Cereals > Cereal Bars"],
  ["Home > Beauty and personal care > Skin care > Facial Skin care > Facial", "https://www.amazon.com/?rh=n=7792268011", "SUBCATEGORY", "Beauty > Makeup > Face"],
  ["Home > Beauty and personal care > Skin care > Facial Skin care > Facial Skin foods", "https://www.amazon.com/?s=grocery&rh=n%3A16322721%2Cp_85%3A247", "CATEGORY", "Pantry > Snacks > Chips"],
  ["Home > Today's deals", "https://www.amazon.com/deals", "OFFERS", "Other > Other > Other"],
  ["Home > Beauty and personal care > Hair care > Hair loss > Hair regrowth", "https://www.amazon.com/?rh=n=18262640011", "SUBCATEGORY", "Beauty > Hair Care > Shampoo"],
  ["Home > Beauty and personal care > Hair care > Scalp treatments", "https://www.amazon.com/?rh=n=23501814011", "SUBCATEGORY", "Beauty > Hair Care > Treatments"],
  ["Home > Colorescience", "https://www.amazon.com/?rh=n=3760911%2C2698024-1a3e-3d64-81df-da5e", "CATEGORY", "Beauty > Personal Care > Other"],
  ["Home > Beauty and personal care > Body Skin care > Body", "https://www.amazon.com/?rh=n=11060691", "SUBCATEGORY", "Beauty > Personal Care > Skin Care"],
  ["Home", "https://www.amazon.com/ref=nav_logo", "HOME", "Other > Other > Other"],
  ["Home > Etta mid", "https://www.amazon.com/?rh=n=3760911%3A4f101fe-a664-39fa-ab63-42cbf7", "BRAND_STORE", "Beauty > Personal Care > Sun Protection"],
  ["Home > Grocery Gourmet Food > Alcoholic Beverages", "https://www.amazon.com/s?grocery&rh=n%3A16310101%2Cn%3A2963371", "CATEGORY", "Beverages > Other > Other"],
  ["Home > Beauty and personal care > Skin care > Sun skin care > Skin sun", "https://www.amazon.com/?rh=n=15239889011", "SUBCATEGORY", "Beauty > Personal Care > Sun Protection"],
  ["Home > Health & Household > Vitamins - Minerals & Supplements > Collagen", "https://www.amazon.com/?keywords=Collagen+Supplements&hpc&rh=n%3A3774", "SUBCATEGORY", "Pharma > Vitamins and Supplements > Collagen"],
  ["Home > Cerave", "https://www.amazon.com/?rh=n=3760911%3A65301844-c540-3a7e-92ab-2049", "BRAND_STORE", "Beauty > Other > Other"],
  ["Home > Beauty and personal care > Skin care > Eyes", "https://www.amazon.com/?rh=n=11061941", "SUBCATEGORY", "Beauty > Personal Care > Face Care"],
  ["Home", "https://www.amazon.com", "HOME", "Other > Other > Other"],
  ["Home > Isdin", "https://www.amazon.com/?rh=n=3760911%3A65301844-c540-3a7e-92ab-204b", "BRAND_STORE", "Beauty > Other > Other"],
  ["Home > Beauty and personal care > Hair care > Hair detanglers", "https://www.amazon.com/?rh=n=10864362011", "SUBCATEGORY", "Beauty > Hair Care > Treatments"],
  ["Home > Grocery and gourmet food > Pantry staples > Cooking and baking", "https://www.amazon.com/?rh=n=18320381", "SUBCATEGORY", "Pantry > Condiments and Sauces > Oil"],
  ["Home > Grocery & Gourmet Food > Snacks & Sweets > Candy & Chocolate", "https://www.amazon.com/?keywords=Ginger+Candy&rh=n%3A16322571", "SUBCATEGORY", "Pantry > Candy > Candies"],
  ["Home > Beauty and personal care > Hair care > Shampoo and conditioner", "https://www.amazon.com/?rh=n=11057651", "SUBCATEGORY", "Beauty > Hair Care > Shampoo"],
  ["Home > Primer day act", "https://www.amazon.com/primebigdealdays", "OFFERS", "Other > Other > Other"],
  ["Home > Holyday Deals", "https://www.amazon.com/gcx/Holiday-Deals/gfhz/events?categoryId=HOL-D", "OFFERS", "Other > Other > Chewing Gum"],
  ["Home > Grocery Gourmet Food > Alcoholic Beverages > Wine", "https://www.amazon.com/s?grocery&rh=n%3A16310101%2Cn%3A2963371", "CATEGORY", "Beverages > Wine > Other"],
  ["Home > Grocery & Gourmet Food > Snacks & Sweets > Chocolate Candy", "https://www.amazon.com/?keywords=Candy+%26+Chocolate+Coated+Fruit&rh=n", "SUBCATEGORY", "Pantry > Chocolate > Other"],
  ["Home > Grocery and gourmet food > Pantry staples > Cooking and baking", "https://www.amazon.com/?rh=n=18320501", "SUBCATEGORY", "Pantry > Condiments and Sauces > Vinegar"],
  ["Home > Beauty and personal care > Skin care > Body", "https://www.amazon.com/?rh=n=11060521", "SUBCATEGORY", "Beauty > Personal Care > Skin Care"],
  ["Home > Grocery & Gourmet Food > Snacks & Sweets > Breakfast & Cereal", "https://www.amazon.com/?keywords=Breakfast+%26+Cereal+Bars&i=n", "CATEGORY", "Pantry > Cereals > Other"],
];

const URL_SEEDS: Seed[] = URL_ROWS.map(([d, url, pageType, cat], i) => {
  const day = String((i % 28) + 1).padStart(2, "0");
  const min = String((i * 17) % 60).padStart(2, "0");
  const stamp = `2026-04-${day}, 11:${min}:00`;
  return { id: `u${i + 1}`, d, store: "Amazon US", cat, c: stamp, u: stamp, type: "URL", value: url, pageType, status: "Active" as SeedStatus };
});

// API seeds. [description, apiOrigin (JSON), pageType, store, category]
const API_ROWS: [string, string, string, string, string][] = [
  ["Home > Merceria > Café", '{"url":"https://www.rappi.com.br/cas/900020403-carrefour-hiper-super-market/merceria"}', "SUBCATEGORY", "Rappi App BR - Carrefour", "Pantry > Coffee > Other"],
  ["Home > Snacks y Frutos secos", '{"categoryName":"Snacks y Frutos secos","subCategoryName":"Otros snacks salados"}', "SUBCATEGORY", "PedidosYa APP AR - Market", "Pantry > Snacks > Other"],
  ["Home", '{"url":"https://www.rappi.com.ec/tiendas/16950-bigdarkstores-nc"}', "HOME", "Rappi APP EC - La Casta", "Other > Other > Other"],
  ["Home > Bebidas > Agua Saborizada", '{"url":"https://www.rappi.com.br/tiendas/160197288/bebidas/agua%20saborizada"}', "SUBCATEGORY", "Uber Eats MX - Chedraui", "Beverages > Waters > Other"],
  ["Home", '{"url":"https://alsuper.com/"}', "HOME", "Al Super APP MX", "Other > Other > Other"],
  ["Home > Men > Grooming > Home fragrances", '{"path":"/men/grooming/home-fragrances/candles"}', "SUBCATEGORY", "Ounass APP AE", "Home Care and Cleaning > Other > Other"],
  ["Home > Dairy & Eggs > Coffee Creamer", '{"url":"https://www.ubereats.com/store/walmart-255-silver-linden-drives/_x2BAy2UUJWEY"}', "SUBCATEGORY", "Uber Eats CA - Walmart", "Fresh and Frozen > Other > Other"],
  ["Home > Breakfast > Oatmeal & Granola", '{"url":"https://www.ubereats.com/store/walmart-255-silver-linden-drives/_x2BAy2UUJWEY"}', "SUBCATEGORY", "Uber Eats CA - Walmart", "Pantry > Cereals > Other"],
  ["Home > Otros licores > Coctel", '{"url":"https://www.rappi.com.co/app/tiendas/900248435/otros%20licores/cocteles"}', "SUBCATEGORY", "Rappi APP CO - Nueva Botella", "Beverages > Other > Other"],
  ["Home > Frutas y Verduras > Frutas", '{"categoryId":"/20/788/24"}', "SUBCATEGORY", "Jumbo APP CL", "Pantry > Snacks > Nuts"],
  ["Home", '{"app_section":"Home"}', "LEGACY", "Albert Heijn APP NL", "Other > Other > Other"],
  ["Home > Panadería y Pastelería", '{"categoryName":"Panadería y Pastelería","subCategoryName":"Tortillas y Tostadas"}', "SUBCATEGORY", "PedidosYa APP PE - Market", "Pantry > Breakfast and Bakery > Other"],
  ["Home Rappi APP MX - Fresko", '{"home_type":"Store Home"}', "HOME", "Rappi APP MX - Fresko", "Other > Other > Other"],
  ["Home > Jugos Y Bebidas > Refrescos", '{"url":"https://alsuper.com/departamento/jugos-y-bebidas-5?department=jugos%20y%20b"}', "SUBCATEGORY", "Al Super APP MX", "Beverages > Ready-to-drink > Other"],
  ["Home > Sucos", '{"url":"https://www.rappi.com.br/cas/900484578-mundial/bebidas/sucos"}', "SUBCATEGORY", "Rappi App BR - Sao Luiz", "Beverages > Juices > Other"],
  ["Home > Cuidado del Cabello > Capilar", '{"url":"https://inkafarma.pe/categoria/cuidado-del-cabello-1/cuidado-profesional/","category"}', "CATEGORY", "Inkafarma PE", "Beauty > Hair Care > Other"],
  ["Home > Bebidas > Jugos y Néctares", '{"url":"https://www.rappi.com.mx/tiendas/1930163835/bebidas/jugos%20y%20nectares"}', "SUBCATEGORY", "Rappi APP MX - La Comer", "Beverages > Juices > Other"],
  ["Home > Bebidas > Jugo", '{"url":"https://www.rappi.com.pe/app/tiendas/1640-wong/bebidas/cafe%20y%20te"}', "SUBCATEGORY", "Rappi APP PE - Wong", "Beverages > Ready-to-drink > Other"],
  ["Home > Beverages > Protein Drinks", '{"url":"https://www.ubereats.com/store/7-eleven-780-6th-st/furl?cvo=R7--_G8HmdmpAA"}', "SUBCATEGORY", "Uber Eats CA - 7 Eleven", "Beverages > Other > Other"],
  ["Home > Lacteos y Huevo > Leche", '{"url":"https://justo.mx/LechesyBebidasVegetales/","category_name":"Lacteos y Bebidas Veg"}', "CATEGORY", "Justo APP MX", "Fresh and Frozen > Milk > Other"],
  ["Home > Bebidas > Aguas", '{"url":"https://www.rappi.com.mx/app/tiendas/1930206027-farmacias-guadalajara/bebidas"}', "HOME", "Rappi App AR - Carrefour", "Beverages > Waters > Other"],
  ["Home > Lácteos y huevos > Yogurt", '{"url":"https://www.ubereats.com/mx/store/la-comer-la-comer-lomas-anahuac/Uvqw3CVJI"}', "SUBCATEGORY", "Uber Eats MX - La Comer", "Fresh and Frozen > Cheese > Other"],
  ["Amazon APP PL - Home", '{"app_section":"Home"}', "HOME", "Amazon APP PL", "Uncategorized"],
  ["Home > Beverages > Coffee", '{"url":"https://www.ubereats.com/store/7-eleven-2057-rutherford-rd/_%40-westburne/BH9"}', "SUBCATEGORY", "Uber Eats CA - 7 Eleven", "Pantry > Coffee > Other"],
  ["Home > Snacks Salados", '{"url":"https://www.rappi.com.pe/tiendas/25318-turbo/snacks%20salados"}', "CATEGORY", "Rappi APP PE - Turbo", "Pantry > Snacks > Other"],
  ["Home > Galletas y Wafers > Galletas dulces", '{"categoryName":"Galletas y Wafers","subCategoryName":"Galletas dulces"}', "SUBCATEGORY", "PedidosYa APP PE - Market", "Pantry > Breakfast and Bakery > Other"],
  ["Home Rappi App BR - Verdemar", '{"home_type":"Store Home"}', "HOME", "Rappi App BR - Verdemar", "Other > Other > Other"],
  ["Home > Jugos y bebidas > Refrescos light", '{"subCategoryId":"refrescos-light"}', "SUBCATEGORY", "Soriana APP MX", "Beverages > Soft Drinks > Other"],
  ["Home > Bebidas > Outras bebidas", '{"url":"https://www.rappi.com.br/lojas/900020372-st-marche/mercearia"}', "CATEGORY", "Rappi App BR - St Marche", "Pantry > Other > Other"],
  ["Home > Offers > Tea, Coffee & Soft drinks", '{"url":"https://www.waitrose.com/ecom/shop/browse/offers/tea_coffee_and_soft_drinks_offers"}', "OFFERS", "Waitrose UK", "Beverages > Other > Other"],
  ["Home > Mercearia", '{"url":"https://www.rappi.com.br/lojas/900141024-zonasul/mercearia"}', "CATEGORY", "Rappi App BR - Zona Sul", "Pantry > Other > Other"],
  ["Home > Confitería > Galletas Rellenas", '{"categoryId":"/47/1041/1057"}', "SUBCATEGORY", "Jumbo APP CL", "Pantry > Breakfast and Bakery > Other"],
  ["Home > Desayunos > Cereales", '{"categoryId":"CATG17553"}', "SUBCATEGORY", "Tottus App PE", "Pantry > Cereals > Other"],
  ["Home > Luly Hypermarket > Condiments", '{"app_section":"Condiments"}', "SUBCATEGORY", "Hunger Station APP SA", "Pantry > Condiments and Sauces > Other"],
  ["Home > Beauty & Hygiene > Sun protection", '{"url":"https://www.easypara.fr/beaute-et-hygiene/soins-solaires/bronzage.html"}', "SUBCATEGORY", "EasyParapharmacie FR", "Beauty > Personal Care > Other"],
];

const API_SEEDS: Seed[] = API_ROWS.map(([d, origin, pageType, store, cat], i) => {
  const day = String((i % 28) + 1).padStart(2, "0");
  const min = String((i * 11) % 60).padStart(2, "0");
  const stamp = `2026-03-${day}, 14:${min}:00`;
  return { id: `a${i + 1}`, d, store, cat, c: stamp, u: stamp, type: "API", value: origin, pageType, status: "Active" as SeedStatus };
});

// PDP seeds (product detail pages). The Discovery key is mandatory for these and
// is the unique handle a discovery run reconciles each product against.
// [description, productUrl, store, category, discoveryKey]
const PDP_ROWS: [string, string, string, string, string][] = [
  ["CeraVe Moisturizing Cream 539g", "https://www.amazon.com/dp/B00TTD9BRC", "Amazon US", "Beauty > Personal Care > Skin Care", "amazon-us-B00TTD9BRC"],
  ["Coca-Cola Original 12 pack", "https://www.amazon.com/dp/B0848P8JKR", "Amazon US", "Beverages > Soft Drinks > Soda", "amazon-us-B0848P8JKR"],
  ["LEGO Marvel Avengers Tower", "https://www.walmart.com/ip/seort/771644551", "Walmart US", "Toys and Games > Building Toys > Building Blocks", "walmart-us-771644551"],
  ["Nescafé Gold Blend 200g", "https://www.amazon.co.uk/dp/B000BG3OA8", "Amazon UK", "Pantry > Coffee > Other", "amazon-uk-B000BG3OA8"],
  ["Sprite Zero Sugar 2L", "https://www.kroger.com/p/sprite-zero/0004900005525", "Kroger US", "Beverages > Soft Drinks > Soda", "kroger-us-0004900005525"],
];

const PDP_SEEDS: Seed[] = PDP_ROWS.map(([d, url, store, cat, discoveryKey], i) => {
  const day = String((i % 28) + 1).padStart(2, "0");
  const min = String((i * 7) % 60).padStart(2, "0");
  const stamp = `2026-06-${day}, 08:${min}:00`;
  return { id: `p${i + 1}`, d, store, cat, c: stamp, u: stamp, type: "PDP", value: url, pageType: "LEGACY", discoveryKey, status: "Active" as SeedStatus };
});

// Real seed corpus ingested from the tasks-api seed export (mapped to the current
// model in ./seedsBulk). The curated demos above stay for the brand showcase + the
// PDP seeds the scenario generator clones for Discovery.
export const INITIAL_SEEDS: Seed[] = [...BASE_SEEDS, ...KEYWORD_SEEDS, ...URL_SEEDS, ...API_SEEDS, ...PDP_SEEDS, ...BULK_KEYWORD_SEEDS, ...BULK_URL_SEEDS];

// Label for the type-specific value field.
export function seedValueLabel(type: SeedType): string {
  switch (type) {
    case "URL": return "URL";
    case "API": return "API";
    case "KEYWORD": return "Keyword";
    case "PDP": return "URL";
  }
}

// The Discovery key is mandatory only for PDP seeds (product pages are grouped /
// reconciled by it). Optional for every other type. Centralised so the form and
// any future validation share one rule.
export function discoveryKeyRequired(type: SeedType): boolean {
  return type === "PDP";
}

// All seeds as persisted (localStorage), falling back to the seed data. Used to
// enforce Discovery-key uniqueness across the whole collection from the form.
export function getSeeds(): Seed[] {
  const list = readPersistedList<Seed>(SEEDS_KEY);
  return list.length ? list : INITIAL_SEEDS;
}

export function emptySeed(type: SeedType): Seed {
  return {
    id: typeof crypto !== "undefined" && crypto.randomUUID ? crypto.randomUUID() : String(Date.now()),
    d: "",
    store: "",
    cat: "",
    c: nowStamp(),
    u: nowStamp(),
    type,
    status: "Active",
    isFromDiscovery: false,
    discoveryKey: "",
    pageType: "",
    value: "",
    ...(type === "KEYWORD" ? { keywordType: "CATEGORY" as KeywordType } : {}),
  };
}
