/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetailersRouteImport } from './routes/retailers'
import { Route as IamRouteImport } from './routes/iam'
import { Route as DataCollectorRouteImport } from './routes/data-collector'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as SeedsApiTimeframesRouteImport } from './routes/seeds-api/timeframes'
import { Route as SeedsApiTagsRouteImport } from './routes/seeds-api/tags'
import { Route as SeedsApiSubscriptionsRouteImport } from './routes/seeds-api/subscriptions'
import { Route as SeedsApiSeedsRouteImport } from './routes/seeds-api/seeds'
import { Route as SeedsApiScrappingOptionsRouteImport } from './routes/seeds-api/scrapping-options'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as SeedsApiProjectsIndexRouteImport } from './routes/seeds-api/projects/index'
import { Route as SeedsApiProjectsNewRouteImport } from './routes/seeds-api/projects/new'
import { Route as SeedsApiProjectsProjectIdRouteImport } from './routes/seeds-api/projects/$projectId'

const RetailersRoute = RetailersRouteImport.update({
  id: '/retailers',
  path: '/retailers',
  getParentRoute: () => rootRouteImport,
} as any)
const IamRoute = IamRouteImport.update({
  id: '/iam',
  path: '/iam',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCollectorRoute = DataCollectorRouteImport.update({
  id: '/data-collector',
  path: '/data-collector',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiTimeframesRoute = SeedsApiTimeframesRouteImport.update({
  id: '/seeds-api/timeframes',
  path: '/seeds-api/timeframes',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiTagsRoute = SeedsApiTagsRouteImport.update({
  id: '/seeds-api/tags',
  path: '/seeds-api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiSubscriptionsRoute = SeedsApiSubscriptionsRouteImport.update({
  id: '/seeds-api/subscriptions',
  path: '/seeds-api/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiSeedsRoute = SeedsApiSeedsRouteImport.update({
  id: '/seeds-api/seeds',
  path: '/seeds-api/seeds',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiScrappingOptionsRoute =
  SeedsApiScrappingOptionsRouteImport.update({
    id: '/seeds-api/scrapping-options',
    path: '/seeds-api/scrapping-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsIndexRoute = SeedsApiProjectsIndexRouteImport.update({
  id: '/seeds-api/projects/',
  path: '/seeds-api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsNewRoute = SeedsApiProjectsNewRouteImport.update({
  id: '/seeds-api/projects/new',
  path: '/seeds-api/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsProjectIdRoute =
  SeedsApiProjectsProjectIdRouteImport.update({
    id: '/seeds-api/projects/$projectId',
    path: '/seeds-api/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/retailers': typeof RetailersRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/seeds': typeof SeedsApiSeedsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/clients/': typeof ClientsIndexRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/projects/': typeof SeedsApiProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/retailers': typeof RetailersRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/seeds': typeof SeedsApiSeedsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/clients': typeof ClientsIndexRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/projects': typeof SeedsApiProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/retailers': typeof RetailersRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/clients/new': typeof ClientsNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/seeds': typeof SeedsApiSeedsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/clients/': typeof ClientsIndexRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/projects/': typeof SeedsApiProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/retailers'
    | '/clients/$clientId'
    | '/clients/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/seeds'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/clients/'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/retailers'
    | '/clients/$clientId'
    | '/clients/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/seeds'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/clients'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/projects'
  id:
    | '__root__'
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/retailers'
    | '/clients/$clientId'
    | '/clients/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/seeds'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/clients/'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkRoute: typeof BulkRoute
  DataCollectorRoute: typeof DataCollectorRoute
  IamRoute: typeof IamRoute
  RetailersRoute: typeof RetailersRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  ClientsNewRoute: typeof ClientsNewRoute
  SeedsApiScrappingOptionsRoute: typeof SeedsApiScrappingOptionsRoute
  SeedsApiSeedsRoute: typeof SeedsApiSeedsRoute
  SeedsApiSubscriptionsRoute: typeof SeedsApiSubscriptionsRoute
  SeedsApiTagsRoute: typeof SeedsApiTagsRoute
  SeedsApiTimeframesRoute: typeof SeedsApiTimeframesRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  SeedsApiProjectsProjectIdRoute: typeof SeedsApiProjectsProjectIdRoute
  SeedsApiProjectsNewRoute: typeof SeedsApiProjectsNewRoute
  SeedsApiProjectsIndexRoute: typeof SeedsApiProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retailers': {
      id: '/retailers'
      path: '/retailers'
      fullPath: '/retailers'
      preLoaderRoute: typeof RetailersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iam': {
      id: '/iam'
      path: '/iam'
      fullPath: '/iam'
      preLoaderRoute: typeof IamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-collector': {
      id: '/data-collector'
      path: '/data-collector'
      fullPath: '/data-collector'
      preLoaderRoute: typeof DataCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/timeframes': {
      id: '/seeds-api/timeframes'
      path: '/seeds-api/timeframes'
      fullPath: '/seeds-api/timeframes'
      preLoaderRoute: typeof SeedsApiTimeframesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/tags': {
      id: '/seeds-api/tags'
      path: '/seeds-api/tags'
      fullPath: '/seeds-api/tags'
      preLoaderRoute: typeof SeedsApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/subscriptions': {
      id: '/seeds-api/subscriptions'
      path: '/seeds-api/subscriptions'
      fullPath: '/seeds-api/subscriptions'
      preLoaderRoute: typeof SeedsApiSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/seeds': {
      id: '/seeds-api/seeds'
      path: '/seeds-api/seeds'
      fullPath: '/seeds-api/seeds'
      preLoaderRoute: typeof SeedsApiSeedsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/scrapping-options': {
      id: '/seeds-api/scrapping-options'
      path: '/seeds-api/scrapping-options'
      fullPath: '/seeds-api/scrapping-options'
      preLoaderRoute: typeof SeedsApiScrappingOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/': {
      id: '/seeds-api/projects/'
      path: '/seeds-api/projects'
      fullPath: '/seeds-api/projects/'
      preLoaderRoute: typeof SeedsApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/new': {
      id: '/seeds-api/projects/new'
      path: '/seeds-api/projects/new'
      fullPath: '/seeds-api/projects/new'
      preLoaderRoute: typeof SeedsApiProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/$projectId': {
      id: '/seeds-api/projects/$projectId'
      path: '/seeds-api/projects/$projectId'
      fullPath: '/seeds-api/projects/$projectId'
      preLoaderRoute: typeof SeedsApiProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkRoute: BulkRoute,
  DataCollectorRoute: DataCollectorRoute,
  IamRoute: IamRoute,
  RetailersRoute: RetailersRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  ClientsNewRoute: ClientsNewRoute,
  SeedsApiScrappingOptionsRoute: SeedsApiScrappingOptionsRoute,
  SeedsApiSeedsRoute: SeedsApiSeedsRoute,
  SeedsApiSubscriptionsRoute: SeedsApiSubscriptionsRoute,
  SeedsApiTagsRoute: SeedsApiTagsRoute,
  SeedsApiTimeframesRoute: SeedsApiTimeframesRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  SeedsApiProjectsProjectIdRoute: SeedsApiProjectsProjectIdRoute,
  SeedsApiProjectsNewRoute: SeedsApiProjectsNewRoute,
  SeedsApiProjectsIndexRoute: SeedsApiProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
