/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IamRouteImport } from './routes/iam'
import { Route as DataCollectorRouteImport } from './routes/data-collector'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as RetailersIndexRouteImport } from './routes/retailers/index'
import { Route as RegionSystemsIndexRouteImport } from './routes/region-systems/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as StoresNewRouteImport } from './routes/stores/new'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as SettingsTimeframesRouteImport } from './routes/settings/timeframes'
import { Route as SettingsTargetsRouteImport } from './routes/settings/targets'
import { Route as SettingsRulesRouteImport } from './routes/settings/rules'
import { Route as SettingsDashboardApplicationsRouteImport } from './routes/settings/dashboard-applications'
import { Route as SettingsCountryGroupsRouteImport } from './routes/settings/country-groups'
import { Route as SettingsCategoriesRouteImport } from './routes/settings/categories'
import { Route as SeedsApiTimeframesRouteImport } from './routes/seeds-api/timeframes'
import { Route as SeedsApiTagsRouteImport } from './routes/seeds-api/tags'
import { Route as SeedsApiSubscriptionsRouteImport } from './routes/seeds-api/subscriptions'
import { Route as SeedsApiScrappingOptionsRouteImport } from './routes/seeds-api/scrapping-options'
import { Route as RetailersNewRouteImport } from './routes/retailers/new'
import { Route as RetailersRetailerIdRouteImport } from './routes/retailers/$retailerId'
import { Route as RegionSystemsNewRouteImport } from './routes/region-systems/new'
import { Route as RegionSystemsRegionIdRouteImport } from './routes/region-systems/$regionId'
import { Route as ProductClientSkusRouteImport } from './routes/product/client-skus'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as SettingsRulesIndexRouteImport } from './routes/settings/rules.index'
import { Route as SettingsDashboardApplicationsIndexRouteImport } from './routes/settings/dashboard-applications.index'
import { Route as SettingsCountryGroupsIndexRouteImport } from './routes/settings/country-groups.index'
import { Route as SettingsCategoriesIndexRouteImport } from './routes/settings/categories.index'
import { Route as SeedsApiSeedsIndexRouteImport } from './routes/seeds-api/seeds/index'
import { Route as SeedsApiProjectsIndexRouteImport } from './routes/seeds-api/projects/index'
import { Route as ProductClientSkusIndexRouteImport } from './routes/product/client-skus.index'
import { Route as ClientsClientIdIndexRouteImport } from './routes/clients/$clientId.index'
import { Route as SettingsRulesNewRouteImport } from './routes/settings/rules.new'
import { Route as SettingsRulesRuleIdRouteImport } from './routes/settings/rules.$ruleId'
import { Route as SettingsDashboardApplicationsAppIdRouteImport } from './routes/settings/dashboard-applications.$appId'
import { Route as SettingsCountryGroupsGroupIdRouteImport } from './routes/settings/country-groups.$groupId'
import { Route as SettingsCategoriesNewRouteImport } from './routes/settings/categories.new'
import { Route as SettingsCategoriesCategoryIdRouteImport } from './routes/settings/categories.$categoryId'
import { Route as SeedsApiSeedsNewRouteImport } from './routes/seeds-api/seeds/new'
import { Route as SeedsApiSeedsSeedIdRouteImport } from './routes/seeds-api/seeds/$seedId'
import { Route as SeedsApiProjectsNewRouteImport } from './routes/seeds-api/projects/new'
import { Route as SeedsApiProjectsProjectIdRouteImport } from './routes/seeds-api/projects/$projectId'
import { Route as ProductClientSkusSkuIdRouteImport } from './routes/product/client-skus.$skuId'
import { Route as SettingsDashboardApplicationsAppIdIndexRouteImport } from './routes/settings/dashboard-applications.$appId.index'
import { Route as ClientsClientIdDataGroupsNewRouteImport } from './routes/clients/$clientId.data-groups.new'
import { Route as ClientsClientIdDataGroupsDataGroupIdRouteImport } from './routes/clients/$clientId.data-groups.$dataGroupId'
import { Route as SettingsDashboardApplicationsAppIdGroupsGroupIdRouteImport } from './routes/settings/dashboard-applications.$appId.groups.$groupId'
import { Route as SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRouteImport } from './routes/settings/dashboard-applications.$appId.groups.$groupId.index'
import { Route as SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRouteImport } from './routes/settings/dashboard-applications.$appId.groups.$groupId.sections.$sectionId'

const IamRoute = IamRouteImport.update({
  id: '/iam',
  path: '/iam',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCollectorRoute = DataCollectorRouteImport.update({
  id: '/data-collector',
  path: '/data-collector',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailersIndexRoute = RetailersIndexRouteImport.update({
  id: '/retailers/',
  path: '/retailers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSystemsIndexRoute = RegionSystemsIndexRouteImport.update({
  id: '/region-systems/',
  path: '/region-systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresNewRoute = StoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTimeframesRoute = SettingsTimeframesRouteImport.update({
  id: '/settings/timeframes',
  path: '/settings/timeframes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTargetsRoute = SettingsTargetsRouteImport.update({
  id: '/settings/targets',
  path: '/settings/targets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesRoute = SettingsRulesRouteImport.update({
  id: '/settings/rules',
  path: '/settings/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsDashboardApplicationsRoute =
  SettingsDashboardApplicationsRouteImport.update({
    id: '/settings/dashboard-applications',
    path: '/settings/dashboard-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const SettingsCountryGroupsRoute = SettingsCountryGroupsRouteImport.update({
  id: '/settings/country-groups',
  path: '/settings/country-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCategoriesRoute = SettingsCategoriesRouteImport.update({
  id: '/settings/categories',
  path: '/settings/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiTimeframesRoute = SeedsApiTimeframesRouteImport.update({
  id: '/seeds-api/timeframes',
  path: '/seeds-api/timeframes',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiTagsRoute = SeedsApiTagsRouteImport.update({
  id: '/seeds-api/tags',
  path: '/seeds-api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiSubscriptionsRoute = SeedsApiSubscriptionsRouteImport.update({
  id: '/seeds-api/subscriptions',
  path: '/seeds-api/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiScrappingOptionsRoute =
  SeedsApiScrappingOptionsRouteImport.update({
    id: '/seeds-api/scrapping-options',
    path: '/seeds-api/scrapping-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const RetailersNewRoute = RetailersNewRouteImport.update({
  id: '/retailers/new',
  path: '/retailers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailersRetailerIdRoute = RetailersRetailerIdRouteImport.update({
  id: '/retailers/$retailerId',
  path: '/retailers/$retailerId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSystemsNewRoute = RegionSystemsNewRouteImport.update({
  id: '/region-systems/new',
  path: '/region-systems/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSystemsRegionIdRoute = RegionSystemsRegionIdRouteImport.update({
  id: '/region-systems/$regionId',
  path: '/region-systems/$regionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductClientSkusRoute = ProductClientSkusRouteImport.update({
  id: '/product/client-skus',
  path: '/product/client-skus',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRulesIndexRoute = SettingsRulesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRulesRoute,
} as any)
const SettingsDashboardApplicationsIndexRoute =
  SettingsDashboardApplicationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsDashboardApplicationsRoute,
  } as any)
const SettingsCountryGroupsIndexRoute =
  SettingsCountryGroupsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsCountryGroupsRoute,
  } as any)
const SettingsCategoriesIndexRoute = SettingsCategoriesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsCategoriesRoute,
} as any)
const SeedsApiSeedsIndexRoute = SeedsApiSeedsIndexRouteImport.update({
  id: '/seeds-api/seeds/',
  path: '/seeds-api/seeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsIndexRoute = SeedsApiProjectsIndexRouteImport.update({
  id: '/seeds-api/projects/',
  path: '/seeds-api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductClientSkusIndexRoute = ProductClientSkusIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductClientSkusRoute,
} as any)
const ClientsClientIdIndexRoute = ClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsClientIdRoute,
} as any)
const SettingsRulesNewRoute = SettingsRulesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SettingsRulesRoute,
} as any)
const SettingsRulesRuleIdRoute = SettingsRulesRuleIdRouteImport.update({
  id: '/$ruleId',
  path: '/$ruleId',
  getParentRoute: () => SettingsRulesRoute,
} as any)
const SettingsDashboardApplicationsAppIdRoute =
  SettingsDashboardApplicationsAppIdRouteImport.update({
    id: '/$appId',
    path: '/$appId',
    getParentRoute: () => SettingsDashboardApplicationsRoute,
  } as any)
const SettingsCountryGroupsGroupIdRoute =
  SettingsCountryGroupsGroupIdRouteImport.update({
    id: '/$groupId',
    path: '/$groupId',
    getParentRoute: () => SettingsCountryGroupsRoute,
  } as any)
const SettingsCategoriesNewRoute = SettingsCategoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SettingsCategoriesRoute,
} as any)
const SettingsCategoriesCategoryIdRoute =
  SettingsCategoriesCategoryIdRouteImport.update({
    id: '/$categoryId',
    path: '/$categoryId',
    getParentRoute: () => SettingsCategoriesRoute,
  } as any)
const SeedsApiSeedsNewRoute = SeedsApiSeedsNewRouteImport.update({
  id: '/seeds-api/seeds/new',
  path: '/seeds-api/seeds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiSeedsSeedIdRoute = SeedsApiSeedsSeedIdRouteImport.update({
  id: '/seeds-api/seeds/$seedId',
  path: '/seeds-api/seeds/$seedId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsNewRoute = SeedsApiProjectsNewRouteImport.update({
  id: '/seeds-api/projects/new',
  path: '/seeds-api/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsProjectIdRoute =
  SeedsApiProjectsProjectIdRouteImport.update({
    id: '/seeds-api/projects/$projectId',
    path: '/seeds-api/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductClientSkusSkuIdRoute = ProductClientSkusSkuIdRouteImport.update({
  id: '/$skuId',
  path: '/$skuId',
  getParentRoute: () => ProductClientSkusRoute,
} as any)
const SettingsDashboardApplicationsAppIdIndexRoute =
  SettingsDashboardApplicationsAppIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsDashboardApplicationsAppIdRoute,
  } as any)
const ClientsClientIdDataGroupsNewRoute =
  ClientsClientIdDataGroupsNewRouteImport.update({
    id: '/data-groups/new',
    path: '/data-groups/new',
    getParentRoute: () => ClientsClientIdRoute,
  } as any)
const ClientsClientIdDataGroupsDataGroupIdRoute =
  ClientsClientIdDataGroupsDataGroupIdRouteImport.update({
    id: '/data-groups/$dataGroupId',
    path: '/data-groups/$dataGroupId',
    getParentRoute: () => ClientsClientIdRoute,
  } as any)
const SettingsDashboardApplicationsAppIdGroupsGroupIdRoute =
  SettingsDashboardApplicationsAppIdGroupsGroupIdRouteImport.update({
    id: '/groups/$groupId',
    path: '/groups/$groupId',
    getParentRoute: () => SettingsDashboardApplicationsAppIdRoute,
  } as any)
const SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRoute =
  SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SettingsDashboardApplicationsAppIdGroupsGroupIdRoute,
  } as any)
const SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRoute =
  SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRouteImport.update(
    {
      id: '/sections/$sectionId',
      path: '/sections/$sectionId',
      getParentRoute: () =>
        SettingsDashboardApplicationsAppIdGroupsGroupIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/product/client-skus': typeof ProductClientSkusRouteWithChildren
  '/region-systems/$regionId': typeof RegionSystemsRegionIdRoute
  '/region-systems/new': typeof RegionSystemsNewRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/retailers/new': typeof RetailersNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/settings/categories': typeof SettingsCategoriesRouteWithChildren
  '/settings/country-groups': typeof SettingsCountryGroupsRouteWithChildren
  '/settings/dashboard-applications': typeof SettingsDashboardApplicationsRouteWithChildren
  '/settings/rules': typeof SettingsRulesRouteWithChildren
  '/settings/targets': typeof SettingsTargetsRoute
  '/settings/timeframes': typeof SettingsTimeframesRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/region-systems/': typeof RegionSystemsIndexRoute
  '/retailers/': typeof RetailersIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/product/client-skus/$skuId': typeof ProductClientSkusSkuIdRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/seeds/$seedId': typeof SeedsApiSeedsSeedIdRoute
  '/seeds-api/seeds/new': typeof SeedsApiSeedsNewRoute
  '/settings/categories/$categoryId': typeof SettingsCategoriesCategoryIdRoute
  '/settings/categories/new': typeof SettingsCategoriesNewRoute
  '/settings/country-groups/$groupId': typeof SettingsCountryGroupsGroupIdRoute
  '/settings/dashboard-applications/$appId': typeof SettingsDashboardApplicationsAppIdRouteWithChildren
  '/settings/rules/$ruleId': typeof SettingsRulesRuleIdRoute
  '/settings/rules/new': typeof SettingsRulesNewRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
  '/product/client-skus/': typeof ProductClientSkusIndexRoute
  '/seeds-api/projects/': typeof SeedsApiProjectsIndexRoute
  '/seeds-api/seeds/': typeof SeedsApiSeedsIndexRoute
  '/settings/categories/': typeof SettingsCategoriesIndexRoute
  '/settings/country-groups/': typeof SettingsCountryGroupsIndexRoute
  '/settings/dashboard-applications/': typeof SettingsDashboardApplicationsIndexRoute
  '/settings/rules/': typeof SettingsRulesIndexRoute
  '/clients/$clientId/data-groups/$dataGroupId': typeof ClientsClientIdDataGroupsDataGroupIdRoute
  '/clients/$clientId/data-groups/new': typeof ClientsClientIdDataGroupsNewRoute
  '/settings/dashboard-applications/$appId/': typeof SettingsDashboardApplicationsAppIdIndexRoute
  '/settings/dashboard-applications/$appId/groups/$groupId': typeof SettingsDashboardApplicationsAppIdGroupsGroupIdRouteWithChildren
  '/settings/dashboard-applications/$appId/groups/$groupId/': typeof SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRoute
  '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId': typeof SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/clients/new': typeof ClientsNewRoute
  '/region-systems/$regionId': typeof RegionSystemsRegionIdRoute
  '/region-systems/new': typeof RegionSystemsNewRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/retailers/new': typeof RetailersNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/settings/targets': typeof SettingsTargetsRoute
  '/settings/timeframes': typeof SettingsTimeframesRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/clients': typeof ClientsIndexRoute
  '/region-systems': typeof RegionSystemsIndexRoute
  '/retailers': typeof RetailersIndexRoute
  '/stores': typeof StoresIndexRoute
  '/product/client-skus/$skuId': typeof ProductClientSkusSkuIdRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/seeds/$seedId': typeof SeedsApiSeedsSeedIdRoute
  '/seeds-api/seeds/new': typeof SeedsApiSeedsNewRoute
  '/settings/categories/$categoryId': typeof SettingsCategoriesCategoryIdRoute
  '/settings/categories/new': typeof SettingsCategoriesNewRoute
  '/settings/country-groups/$groupId': typeof SettingsCountryGroupsGroupIdRoute
  '/settings/rules/$ruleId': typeof SettingsRulesRuleIdRoute
  '/settings/rules/new': typeof SettingsRulesNewRoute
  '/clients/$clientId': typeof ClientsClientIdIndexRoute
  '/product/client-skus': typeof ProductClientSkusIndexRoute
  '/seeds-api/projects': typeof SeedsApiProjectsIndexRoute
  '/seeds-api/seeds': typeof SeedsApiSeedsIndexRoute
  '/settings/categories': typeof SettingsCategoriesIndexRoute
  '/settings/country-groups': typeof SettingsCountryGroupsIndexRoute
  '/settings/dashboard-applications': typeof SettingsDashboardApplicationsIndexRoute
  '/settings/rules': typeof SettingsRulesIndexRoute
  '/clients/$clientId/data-groups/$dataGroupId': typeof ClientsClientIdDataGroupsDataGroupIdRoute
  '/clients/$clientId/data-groups/new': typeof ClientsClientIdDataGroupsNewRoute
  '/settings/dashboard-applications/$appId': typeof SettingsDashboardApplicationsAppIdIndexRoute
  '/settings/dashboard-applications/$appId/groups/$groupId': typeof SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRoute
  '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId': typeof SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/product/client-skus': typeof ProductClientSkusRouteWithChildren
  '/region-systems/$regionId': typeof RegionSystemsRegionIdRoute
  '/region-systems/new': typeof RegionSystemsNewRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/retailers/new': typeof RetailersNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/settings/categories': typeof SettingsCategoriesRouteWithChildren
  '/settings/country-groups': typeof SettingsCountryGroupsRouteWithChildren
  '/settings/dashboard-applications': typeof SettingsDashboardApplicationsRouteWithChildren
  '/settings/rules': typeof SettingsRulesRouteWithChildren
  '/settings/targets': typeof SettingsTargetsRoute
  '/settings/timeframes': typeof SettingsTimeframesRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/region-systems/': typeof RegionSystemsIndexRoute
  '/retailers/': typeof RetailersIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/product/client-skus/$skuId': typeof ProductClientSkusSkuIdRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/seeds/$seedId': typeof SeedsApiSeedsSeedIdRoute
  '/seeds-api/seeds/new': typeof SeedsApiSeedsNewRoute
  '/settings/categories/$categoryId': typeof SettingsCategoriesCategoryIdRoute
  '/settings/categories/new': typeof SettingsCategoriesNewRoute
  '/settings/country-groups/$groupId': typeof SettingsCountryGroupsGroupIdRoute
  '/settings/dashboard-applications/$appId': typeof SettingsDashboardApplicationsAppIdRouteWithChildren
  '/settings/rules/$ruleId': typeof SettingsRulesRuleIdRoute
  '/settings/rules/new': typeof SettingsRulesNewRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
  '/product/client-skus/': typeof ProductClientSkusIndexRoute
  '/seeds-api/projects/': typeof SeedsApiProjectsIndexRoute
  '/seeds-api/seeds/': typeof SeedsApiSeedsIndexRoute
  '/settings/categories/': typeof SettingsCategoriesIndexRoute
  '/settings/country-groups/': typeof SettingsCountryGroupsIndexRoute
  '/settings/dashboard-applications/': typeof SettingsDashboardApplicationsIndexRoute
  '/settings/rules/': typeof SettingsRulesIndexRoute
  '/clients/$clientId/data-groups/$dataGroupId': typeof ClientsClientIdDataGroupsDataGroupIdRoute
  '/clients/$clientId/data-groups/new': typeof ClientsClientIdDataGroupsNewRoute
  '/settings/dashboard-applications/$appId/': typeof SettingsDashboardApplicationsAppIdIndexRoute
  '/settings/dashboard-applications/$appId/groups/$groupId': typeof SettingsDashboardApplicationsAppIdGroupsGroupIdRouteWithChildren
  '/settings/dashboard-applications/$appId/groups/$groupId/': typeof SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRoute
  '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId': typeof SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/clients/$clientId'
    | '/clients/new'
    | '/product/client-skus'
    | '/region-systems/$regionId'
    | '/region-systems/new'
    | '/retailers/$retailerId'
    | '/retailers/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/settings/categories'
    | '/settings/country-groups'
    | '/settings/dashboard-applications'
    | '/settings/rules'
    | '/settings/targets'
    | '/settings/timeframes'
    | '/stores/$storeId'
    | '/stores/new'
    | '/clients/'
    | '/region-systems/'
    | '/retailers/'
    | '/stores/'
    | '/product/client-skus/$skuId'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/seeds/$seedId'
    | '/seeds-api/seeds/new'
    | '/settings/categories/$categoryId'
    | '/settings/categories/new'
    | '/settings/country-groups/$groupId'
    | '/settings/dashboard-applications/$appId'
    | '/settings/rules/$ruleId'
    | '/settings/rules/new'
    | '/clients/$clientId/'
    | '/product/client-skus/'
    | '/seeds-api/projects/'
    | '/seeds-api/seeds/'
    | '/settings/categories/'
    | '/settings/country-groups/'
    | '/settings/dashboard-applications/'
    | '/settings/rules/'
    | '/clients/$clientId/data-groups/$dataGroupId'
    | '/clients/$clientId/data-groups/new'
    | '/settings/dashboard-applications/$appId/'
    | '/settings/dashboard-applications/$appId/groups/$groupId'
    | '/settings/dashboard-applications/$appId/groups/$groupId/'
    | '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/clients/new'
    | '/region-systems/$regionId'
    | '/region-systems/new'
    | '/retailers/$retailerId'
    | '/retailers/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/settings/targets'
    | '/settings/timeframes'
    | '/stores/$storeId'
    | '/stores/new'
    | '/clients'
    | '/region-systems'
    | '/retailers'
    | '/stores'
    | '/product/client-skus/$skuId'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/seeds/$seedId'
    | '/seeds-api/seeds/new'
    | '/settings/categories/$categoryId'
    | '/settings/categories/new'
    | '/settings/country-groups/$groupId'
    | '/settings/rules/$ruleId'
    | '/settings/rules/new'
    | '/clients/$clientId'
    | '/product/client-skus'
    | '/seeds-api/projects'
    | '/seeds-api/seeds'
    | '/settings/categories'
    | '/settings/country-groups'
    | '/settings/dashboard-applications'
    | '/settings/rules'
    | '/clients/$clientId/data-groups/$dataGroupId'
    | '/clients/$clientId/data-groups/new'
    | '/settings/dashboard-applications/$appId'
    | '/settings/dashboard-applications/$appId/groups/$groupId'
    | '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/clients/$clientId'
    | '/clients/new'
    | '/product/client-skus'
    | '/region-systems/$regionId'
    | '/region-systems/new'
    | '/retailers/$retailerId'
    | '/retailers/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/settings/categories'
    | '/settings/country-groups'
    | '/settings/dashboard-applications'
    | '/settings/rules'
    | '/settings/targets'
    | '/settings/timeframes'
    | '/stores/$storeId'
    | '/stores/new'
    | '/clients/'
    | '/region-systems/'
    | '/retailers/'
    | '/stores/'
    | '/product/client-skus/$skuId'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/seeds/$seedId'
    | '/seeds-api/seeds/new'
    | '/settings/categories/$categoryId'
    | '/settings/categories/new'
    | '/settings/country-groups/$groupId'
    | '/settings/dashboard-applications/$appId'
    | '/settings/rules/$ruleId'
    | '/settings/rules/new'
    | '/clients/$clientId/'
    | '/product/client-skus/'
    | '/seeds-api/projects/'
    | '/seeds-api/seeds/'
    | '/settings/categories/'
    | '/settings/country-groups/'
    | '/settings/dashboard-applications/'
    | '/settings/rules/'
    | '/clients/$clientId/data-groups/$dataGroupId'
    | '/clients/$clientId/data-groups/new'
    | '/settings/dashboard-applications/$appId/'
    | '/settings/dashboard-applications/$appId/groups/$groupId'
    | '/settings/dashboard-applications/$appId/groups/$groupId/'
    | '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkRoute: typeof BulkRoute
  DataCollectorRoute: typeof DataCollectorRoute
  IamRoute: typeof IamRoute
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
  ProductClientSkusRoute: typeof ProductClientSkusRouteWithChildren
  RegionSystemsRegionIdRoute: typeof RegionSystemsRegionIdRoute
  RegionSystemsNewRoute: typeof RegionSystemsNewRoute
  RetailersRetailerIdRoute: typeof RetailersRetailerIdRoute
  RetailersNewRoute: typeof RetailersNewRoute
  SeedsApiScrappingOptionsRoute: typeof SeedsApiScrappingOptionsRoute
  SeedsApiSubscriptionsRoute: typeof SeedsApiSubscriptionsRoute
  SeedsApiTagsRoute: typeof SeedsApiTagsRoute
  SeedsApiTimeframesRoute: typeof SeedsApiTimeframesRoute
  SettingsCategoriesRoute: typeof SettingsCategoriesRouteWithChildren
  SettingsCountryGroupsRoute: typeof SettingsCountryGroupsRouteWithChildren
  SettingsDashboardApplicationsRoute: typeof SettingsDashboardApplicationsRouteWithChildren
  SettingsRulesRoute: typeof SettingsRulesRouteWithChildren
  SettingsTargetsRoute: typeof SettingsTargetsRoute
  SettingsTimeframesRoute: typeof SettingsTimeframesRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  StoresNewRoute: typeof StoresNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  RegionSystemsIndexRoute: typeof RegionSystemsIndexRoute
  RetailersIndexRoute: typeof RetailersIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  SeedsApiProjectsProjectIdRoute: typeof SeedsApiProjectsProjectIdRoute
  SeedsApiProjectsNewRoute: typeof SeedsApiProjectsNewRoute
  SeedsApiSeedsSeedIdRoute: typeof SeedsApiSeedsSeedIdRoute
  SeedsApiSeedsNewRoute: typeof SeedsApiSeedsNewRoute
  SeedsApiProjectsIndexRoute: typeof SeedsApiProjectsIndexRoute
  SeedsApiSeedsIndexRoute: typeof SeedsApiSeedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iam': {
      id: '/iam'
      path: '/iam'
      fullPath: '/iam'
      preLoaderRoute: typeof IamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-collector': {
      id: '/data-collector'
      path: '/data-collector'
      fullPath: '/data-collector'
      preLoaderRoute: typeof DataCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/': {
      id: '/retailers/'
      path: '/retailers'
      fullPath: '/retailers/'
      preLoaderRoute: typeof RetailersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region-systems/': {
      id: '/region-systems/'
      path: '/region-systems'
      fullPath: '/region-systems/'
      preLoaderRoute: typeof RegionSystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/new': {
      id: '/stores/new'
      path: '/stores/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof StoresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/timeframes': {
      id: '/settings/timeframes'
      path: '/settings/timeframes'
      fullPath: '/settings/timeframes'
      preLoaderRoute: typeof SettingsTimeframesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/targets': {
      id: '/settings/targets'
      path: '/settings/targets'
      fullPath: '/settings/targets'
      preLoaderRoute: typeof SettingsTargetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rules': {
      id: '/settings/rules'
      path: '/settings/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof SettingsRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/dashboard-applications': {
      id: '/settings/dashboard-applications'
      path: '/settings/dashboard-applications'
      fullPath: '/settings/dashboard-applications'
      preLoaderRoute: typeof SettingsDashboardApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/country-groups': {
      id: '/settings/country-groups'
      path: '/settings/country-groups'
      fullPath: '/settings/country-groups'
      preLoaderRoute: typeof SettingsCountryGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/categories': {
      id: '/settings/categories'
      path: '/settings/categories'
      fullPath: '/settings/categories'
      preLoaderRoute: typeof SettingsCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/timeframes': {
      id: '/seeds-api/timeframes'
      path: '/seeds-api/timeframes'
      fullPath: '/seeds-api/timeframes'
      preLoaderRoute: typeof SeedsApiTimeframesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/tags': {
      id: '/seeds-api/tags'
      path: '/seeds-api/tags'
      fullPath: '/seeds-api/tags'
      preLoaderRoute: typeof SeedsApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/subscriptions': {
      id: '/seeds-api/subscriptions'
      path: '/seeds-api/subscriptions'
      fullPath: '/seeds-api/subscriptions'
      preLoaderRoute: typeof SeedsApiSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/scrapping-options': {
      id: '/seeds-api/scrapping-options'
      path: '/seeds-api/scrapping-options'
      fullPath: '/seeds-api/scrapping-options'
      preLoaderRoute: typeof SeedsApiScrappingOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/new': {
      id: '/retailers/new'
      path: '/retailers/new'
      fullPath: '/retailers/new'
      preLoaderRoute: typeof RetailersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/$retailerId': {
      id: '/retailers/$retailerId'
      path: '/retailers/$retailerId'
      fullPath: '/retailers/$retailerId'
      preLoaderRoute: typeof RetailersRetailerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region-systems/new': {
      id: '/region-systems/new'
      path: '/region-systems/new'
      fullPath: '/region-systems/new'
      preLoaderRoute: typeof RegionSystemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region-systems/$regionId': {
      id: '/region-systems/$regionId'
      path: '/region-systems/$regionId'
      fullPath: '/region-systems/$regionId'
      preLoaderRoute: typeof RegionSystemsRegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/client-skus': {
      id: '/product/client-skus'
      path: '/product/client-skus'
      fullPath: '/product/client-skus'
      preLoaderRoute: typeof ProductClientSkusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/rules/': {
      id: '/settings/rules/'
      path: '/'
      fullPath: '/settings/rules/'
      preLoaderRoute: typeof SettingsRulesIndexRouteImport
      parentRoute: typeof SettingsRulesRoute
    }
    '/settings/dashboard-applications/': {
      id: '/settings/dashboard-applications/'
      path: '/'
      fullPath: '/settings/dashboard-applications/'
      preLoaderRoute: typeof SettingsDashboardApplicationsIndexRouteImport
      parentRoute: typeof SettingsDashboardApplicationsRoute
    }
    '/settings/country-groups/': {
      id: '/settings/country-groups/'
      path: '/'
      fullPath: '/settings/country-groups/'
      preLoaderRoute: typeof SettingsCountryGroupsIndexRouteImport
      parentRoute: typeof SettingsCountryGroupsRoute
    }
    '/settings/categories/': {
      id: '/settings/categories/'
      path: '/'
      fullPath: '/settings/categories/'
      preLoaderRoute: typeof SettingsCategoriesIndexRouteImport
      parentRoute: typeof SettingsCategoriesRoute
    }
    '/seeds-api/seeds/': {
      id: '/seeds-api/seeds/'
      path: '/seeds-api/seeds'
      fullPath: '/seeds-api/seeds/'
      preLoaderRoute: typeof SeedsApiSeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/': {
      id: '/seeds-api/projects/'
      path: '/seeds-api/projects'
      fullPath: '/seeds-api/projects/'
      preLoaderRoute: typeof SeedsApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/client-skus/': {
      id: '/product/client-skus/'
      path: '/'
      fullPath: '/product/client-skus/'
      preLoaderRoute: typeof ProductClientSkusIndexRouteImport
      parentRoute: typeof ProductClientSkusRoute
    }
    '/clients/$clientId/': {
      id: '/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof ClientsClientIdIndexRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/settings/rules/new': {
      id: '/settings/rules/new'
      path: '/new'
      fullPath: '/settings/rules/new'
      preLoaderRoute: typeof SettingsRulesNewRouteImport
      parentRoute: typeof SettingsRulesRoute
    }
    '/settings/rules/$ruleId': {
      id: '/settings/rules/$ruleId'
      path: '/$ruleId'
      fullPath: '/settings/rules/$ruleId'
      preLoaderRoute: typeof SettingsRulesRuleIdRouteImport
      parentRoute: typeof SettingsRulesRoute
    }
    '/settings/dashboard-applications/$appId': {
      id: '/settings/dashboard-applications/$appId'
      path: '/$appId'
      fullPath: '/settings/dashboard-applications/$appId'
      preLoaderRoute: typeof SettingsDashboardApplicationsAppIdRouteImport
      parentRoute: typeof SettingsDashboardApplicationsRoute
    }
    '/settings/country-groups/$groupId': {
      id: '/settings/country-groups/$groupId'
      path: '/$groupId'
      fullPath: '/settings/country-groups/$groupId'
      preLoaderRoute: typeof SettingsCountryGroupsGroupIdRouteImport
      parentRoute: typeof SettingsCountryGroupsRoute
    }
    '/settings/categories/new': {
      id: '/settings/categories/new'
      path: '/new'
      fullPath: '/settings/categories/new'
      preLoaderRoute: typeof SettingsCategoriesNewRouteImport
      parentRoute: typeof SettingsCategoriesRoute
    }
    '/settings/categories/$categoryId': {
      id: '/settings/categories/$categoryId'
      path: '/$categoryId'
      fullPath: '/settings/categories/$categoryId'
      preLoaderRoute: typeof SettingsCategoriesCategoryIdRouteImport
      parentRoute: typeof SettingsCategoriesRoute
    }
    '/seeds-api/seeds/new': {
      id: '/seeds-api/seeds/new'
      path: '/seeds-api/seeds/new'
      fullPath: '/seeds-api/seeds/new'
      preLoaderRoute: typeof SeedsApiSeedsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/seeds/$seedId': {
      id: '/seeds-api/seeds/$seedId'
      path: '/seeds-api/seeds/$seedId'
      fullPath: '/seeds-api/seeds/$seedId'
      preLoaderRoute: typeof SeedsApiSeedsSeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/new': {
      id: '/seeds-api/projects/new'
      path: '/seeds-api/projects/new'
      fullPath: '/seeds-api/projects/new'
      preLoaderRoute: typeof SeedsApiProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/$projectId': {
      id: '/seeds-api/projects/$projectId'
      path: '/seeds-api/projects/$projectId'
      fullPath: '/seeds-api/projects/$projectId'
      preLoaderRoute: typeof SeedsApiProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/client-skus/$skuId': {
      id: '/product/client-skus/$skuId'
      path: '/$skuId'
      fullPath: '/product/client-skus/$skuId'
      preLoaderRoute: typeof ProductClientSkusSkuIdRouteImport
      parentRoute: typeof ProductClientSkusRoute
    }
    '/settings/dashboard-applications/$appId/': {
      id: '/settings/dashboard-applications/$appId/'
      path: '/'
      fullPath: '/settings/dashboard-applications/$appId/'
      preLoaderRoute: typeof SettingsDashboardApplicationsAppIdIndexRouteImport
      parentRoute: typeof SettingsDashboardApplicationsAppIdRoute
    }
    '/clients/$clientId/data-groups/new': {
      id: '/clients/$clientId/data-groups/new'
      path: '/data-groups/new'
      fullPath: '/clients/$clientId/data-groups/new'
      preLoaderRoute: typeof ClientsClientIdDataGroupsNewRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/clients/$clientId/data-groups/$dataGroupId': {
      id: '/clients/$clientId/data-groups/$dataGroupId'
      path: '/data-groups/$dataGroupId'
      fullPath: '/clients/$clientId/data-groups/$dataGroupId'
      preLoaderRoute: typeof ClientsClientIdDataGroupsDataGroupIdRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/settings/dashboard-applications/$appId/groups/$groupId': {
      id: '/settings/dashboard-applications/$appId/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/settings/dashboard-applications/$appId/groups/$groupId'
      preLoaderRoute: typeof SettingsDashboardApplicationsAppIdGroupsGroupIdRouteImport
      parentRoute: typeof SettingsDashboardApplicationsAppIdRoute
    }
    '/settings/dashboard-applications/$appId/groups/$groupId/': {
      id: '/settings/dashboard-applications/$appId/groups/$groupId/'
      path: '/'
      fullPath: '/settings/dashboard-applications/$appId/groups/$groupId/'
      preLoaderRoute: typeof SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRouteImport
      parentRoute: typeof SettingsDashboardApplicationsAppIdGroupsGroupIdRoute
    }
    '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId': {
      id: '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId'
      path: '/sections/$sectionId'
      fullPath: '/settings/dashboard-applications/$appId/groups/$groupId/sections/$sectionId'
      preLoaderRoute: typeof SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRouteImport
      parentRoute: typeof SettingsDashboardApplicationsAppIdGroupsGroupIdRoute
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdIndexRoute: typeof ClientsClientIdIndexRoute
  ClientsClientIdDataGroupsDataGroupIdRoute: typeof ClientsClientIdDataGroupsDataGroupIdRoute
  ClientsClientIdDataGroupsNewRoute: typeof ClientsClientIdDataGroupsNewRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdIndexRoute: ClientsClientIdIndexRoute,
  ClientsClientIdDataGroupsDataGroupIdRoute:
    ClientsClientIdDataGroupsDataGroupIdRoute,
  ClientsClientIdDataGroupsNewRoute: ClientsClientIdDataGroupsNewRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

interface ProductClientSkusRouteChildren {
  ProductClientSkusSkuIdRoute: typeof ProductClientSkusSkuIdRoute
  ProductClientSkusIndexRoute: typeof ProductClientSkusIndexRoute
}

const ProductClientSkusRouteChildren: ProductClientSkusRouteChildren = {
  ProductClientSkusSkuIdRoute: ProductClientSkusSkuIdRoute,
  ProductClientSkusIndexRoute: ProductClientSkusIndexRoute,
}

const ProductClientSkusRouteWithChildren =
  ProductClientSkusRoute._addFileChildren(ProductClientSkusRouteChildren)

interface SettingsCategoriesRouteChildren {
  SettingsCategoriesCategoryIdRoute: typeof SettingsCategoriesCategoryIdRoute
  SettingsCategoriesNewRoute: typeof SettingsCategoriesNewRoute
  SettingsCategoriesIndexRoute: typeof SettingsCategoriesIndexRoute
}

const SettingsCategoriesRouteChildren: SettingsCategoriesRouteChildren = {
  SettingsCategoriesCategoryIdRoute: SettingsCategoriesCategoryIdRoute,
  SettingsCategoriesNewRoute: SettingsCategoriesNewRoute,
  SettingsCategoriesIndexRoute: SettingsCategoriesIndexRoute,
}

const SettingsCategoriesRouteWithChildren =
  SettingsCategoriesRoute._addFileChildren(SettingsCategoriesRouteChildren)

interface SettingsCountryGroupsRouteChildren {
  SettingsCountryGroupsGroupIdRoute: typeof SettingsCountryGroupsGroupIdRoute
  SettingsCountryGroupsIndexRoute: typeof SettingsCountryGroupsIndexRoute
}

const SettingsCountryGroupsRouteChildren: SettingsCountryGroupsRouteChildren = {
  SettingsCountryGroupsGroupIdRoute: SettingsCountryGroupsGroupIdRoute,
  SettingsCountryGroupsIndexRoute: SettingsCountryGroupsIndexRoute,
}

const SettingsCountryGroupsRouteWithChildren =
  SettingsCountryGroupsRoute._addFileChildren(
    SettingsCountryGroupsRouteChildren,
  )

interface SettingsDashboardApplicationsAppIdGroupsGroupIdRouteChildren {
  SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRoute: typeof SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRoute
  SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRoute: typeof SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRoute
}

const SettingsDashboardApplicationsAppIdGroupsGroupIdRouteChildren: SettingsDashboardApplicationsAppIdGroupsGroupIdRouteChildren =
  {
    SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRoute:
      SettingsDashboardApplicationsAppIdGroupsGroupIdIndexRoute,
    SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRoute:
      SettingsDashboardApplicationsAppIdGroupsGroupIdSectionsSectionIdRoute,
  }

const SettingsDashboardApplicationsAppIdGroupsGroupIdRouteWithChildren =
  SettingsDashboardApplicationsAppIdGroupsGroupIdRoute._addFileChildren(
    SettingsDashboardApplicationsAppIdGroupsGroupIdRouteChildren,
  )

interface SettingsDashboardApplicationsAppIdRouteChildren {
  SettingsDashboardApplicationsAppIdIndexRoute: typeof SettingsDashboardApplicationsAppIdIndexRoute
  SettingsDashboardApplicationsAppIdGroupsGroupIdRoute: typeof SettingsDashboardApplicationsAppIdGroupsGroupIdRouteWithChildren
}

const SettingsDashboardApplicationsAppIdRouteChildren: SettingsDashboardApplicationsAppIdRouteChildren =
  {
    SettingsDashboardApplicationsAppIdIndexRoute:
      SettingsDashboardApplicationsAppIdIndexRoute,
    SettingsDashboardApplicationsAppIdGroupsGroupIdRoute:
      SettingsDashboardApplicationsAppIdGroupsGroupIdRouteWithChildren,
  }

const SettingsDashboardApplicationsAppIdRouteWithChildren =
  SettingsDashboardApplicationsAppIdRoute._addFileChildren(
    SettingsDashboardApplicationsAppIdRouteChildren,
  )

interface SettingsDashboardApplicationsRouteChildren {
  SettingsDashboardApplicationsAppIdRoute: typeof SettingsDashboardApplicationsAppIdRouteWithChildren
  SettingsDashboardApplicationsIndexRoute: typeof SettingsDashboardApplicationsIndexRoute
}

const SettingsDashboardApplicationsRouteChildren: SettingsDashboardApplicationsRouteChildren =
  {
    SettingsDashboardApplicationsAppIdRoute:
      SettingsDashboardApplicationsAppIdRouteWithChildren,
    SettingsDashboardApplicationsIndexRoute:
      SettingsDashboardApplicationsIndexRoute,
  }

const SettingsDashboardApplicationsRouteWithChildren =
  SettingsDashboardApplicationsRoute._addFileChildren(
    SettingsDashboardApplicationsRouteChildren,
  )

interface SettingsRulesRouteChildren {
  SettingsRulesRuleIdRoute: typeof SettingsRulesRuleIdRoute
  SettingsRulesNewRoute: typeof SettingsRulesNewRoute
  SettingsRulesIndexRoute: typeof SettingsRulesIndexRoute
}

const SettingsRulesRouteChildren: SettingsRulesRouteChildren = {
  SettingsRulesRuleIdRoute: SettingsRulesRuleIdRoute,
  SettingsRulesNewRoute: SettingsRulesNewRoute,
  SettingsRulesIndexRoute: SettingsRulesIndexRoute,
}

const SettingsRulesRouteWithChildren = SettingsRulesRoute._addFileChildren(
  SettingsRulesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkRoute: BulkRoute,
  DataCollectorRoute: DataCollectorRoute,
  IamRoute: IamRoute,
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
  ProductClientSkusRoute: ProductClientSkusRouteWithChildren,
  RegionSystemsRegionIdRoute: RegionSystemsRegionIdRoute,
  RegionSystemsNewRoute: RegionSystemsNewRoute,
  RetailersRetailerIdRoute: RetailersRetailerIdRoute,
  RetailersNewRoute: RetailersNewRoute,
  SeedsApiScrappingOptionsRoute: SeedsApiScrappingOptionsRoute,
  SeedsApiSubscriptionsRoute: SeedsApiSubscriptionsRoute,
  SeedsApiTagsRoute: SeedsApiTagsRoute,
  SeedsApiTimeframesRoute: SeedsApiTimeframesRoute,
  SettingsCategoriesRoute: SettingsCategoriesRouteWithChildren,
  SettingsCountryGroupsRoute: SettingsCountryGroupsRouteWithChildren,
  SettingsDashboardApplicationsRoute:
    SettingsDashboardApplicationsRouteWithChildren,
  SettingsRulesRoute: SettingsRulesRouteWithChildren,
  SettingsTargetsRoute: SettingsTargetsRoute,
  SettingsTimeframesRoute: SettingsTimeframesRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  StoresNewRoute: StoresNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  RegionSystemsIndexRoute: RegionSystemsIndexRoute,
  RetailersIndexRoute: RetailersIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  SeedsApiProjectsProjectIdRoute: SeedsApiProjectsProjectIdRoute,
  SeedsApiProjectsNewRoute: SeedsApiProjectsNewRoute,
  SeedsApiSeedsSeedIdRoute: SeedsApiSeedsSeedIdRoute,
  SeedsApiSeedsNewRoute: SeedsApiSeedsNewRoute,
  SeedsApiProjectsIndexRoute: SeedsApiProjectsIndexRoute,
  SeedsApiSeedsIndexRoute: SeedsApiSeedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
