/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IamRouteImport } from './routes/iam'
import { Route as DataCollectorRouteImport } from './routes/data-collector'
import { Route as BulkRouteImport } from './routes/bulk'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresIndexRouteImport } from './routes/stores/index'
import { Route as RetailersIndexRouteImport } from './routes/retailers/index'
import { Route as RegionSystemsIndexRouteImport } from './routes/region-systems/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as StoresNewRouteImport } from './routes/stores/new'
import { Route as StoresStoreIdRouteImport } from './routes/stores/$storeId'
import { Route as SeedsApiTimeframesRouteImport } from './routes/seeds-api/timeframes'
import { Route as SeedsApiTagsRouteImport } from './routes/seeds-api/tags'
import { Route as SeedsApiSubscriptionsRouteImport } from './routes/seeds-api/subscriptions'
import { Route as SeedsApiScrappingOptionsRouteImport } from './routes/seeds-api/scrapping-options'
import { Route as RetailersNewRouteImport } from './routes/retailers/new'
import { Route as RetailersRetailerIdRouteImport } from './routes/retailers/$retailerId'
import { Route as RegionSystemsNewRouteImport } from './routes/region-systems/new'
import { Route as RegionSystemsRegionIdRouteImport } from './routes/region-systems/$regionId'
import { Route as ProductClientSkusRouteImport } from './routes/product/client-skus'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsClientIdRouteImport } from './routes/clients/$clientId'
import { Route as SeedsApiSeedsIndexRouteImport } from './routes/seeds-api/seeds/index'
import { Route as SeedsApiProjectsIndexRouteImport } from './routes/seeds-api/projects/index'
import { Route as ClientsClientIdIndexRouteImport } from './routes/clients/$clientId.index'
import { Route as SeedsApiSeedsNewRouteImport } from './routes/seeds-api/seeds/new'
import { Route as SeedsApiSeedsSeedIdRouteImport } from './routes/seeds-api/seeds/$seedId'
import { Route as SeedsApiProjectsNewRouteImport } from './routes/seeds-api/projects/new'
import { Route as SeedsApiProjectsProjectIdRouteImport } from './routes/seeds-api/projects/$projectId'
import { Route as ClientsClientIdDataGroupsNewRouteImport } from './routes/clients/$clientId.data-groups.new'
import { Route as ClientsClientIdDataGroupsDataGroupIdRouteImport } from './routes/clients/$clientId.data-groups.$dataGroupId'

const IamRoute = IamRouteImport.update({
  id: '/iam',
  path: '/iam',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCollectorRoute = DataCollectorRouteImport.update({
  id: '/data-collector',
  path: '/data-collector',
  getParentRoute: () => rootRouteImport,
} as any)
const BulkRoute = BulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: '/stores/',
  path: '/stores/',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailersIndexRoute = RetailersIndexRouteImport.update({
  id: '/retailers/',
  path: '/retailers/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSystemsIndexRoute = RegionSystemsIndexRouteImport.update({
  id: '/region-systems/',
  path: '/region-systems/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresNewRoute = StoresNewRouteImport.update({
  id: '/stores/new',
  path: '/stores/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiTimeframesRoute = SeedsApiTimeframesRouteImport.update({
  id: '/seeds-api/timeframes',
  path: '/seeds-api/timeframes',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiTagsRoute = SeedsApiTagsRouteImport.update({
  id: '/seeds-api/tags',
  path: '/seeds-api/tags',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiSubscriptionsRoute = SeedsApiSubscriptionsRouteImport.update({
  id: '/seeds-api/subscriptions',
  path: '/seeds-api/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiScrappingOptionsRoute =
  SeedsApiScrappingOptionsRouteImport.update({
    id: '/seeds-api/scrapping-options',
    path: '/seeds-api/scrapping-options',
    getParentRoute: () => rootRouteImport,
  } as any)
const RetailersNewRoute = RetailersNewRouteImport.update({
  id: '/retailers/new',
  path: '/retailers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailersRetailerIdRoute = RetailersRetailerIdRouteImport.update({
  id: '/retailers/$retailerId',
  path: '/retailers/$retailerId',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSystemsNewRoute = RegionSystemsNewRouteImport.update({
  id: '/region-systems/new',
  path: '/region-systems/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionSystemsRegionIdRoute = RegionSystemsRegionIdRouteImport.update({
  id: '/region-systems/$regionId',
  path: '/region-systems/$regionId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductClientSkusRoute = ProductClientSkusRouteImport.update({
  id: '/product/client-skus',
  path: '/product/client-skus',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiSeedsIndexRoute = SeedsApiSeedsIndexRouteImport.update({
  id: '/seeds-api/seeds/',
  path: '/seeds-api/seeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsIndexRoute = SeedsApiProjectsIndexRouteImport.update({
  id: '/seeds-api/projects/',
  path: '/seeds-api/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdIndexRoute = ClientsClientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientsClientIdRoute,
} as any)
const SeedsApiSeedsNewRoute = SeedsApiSeedsNewRouteImport.update({
  id: '/seeds-api/seeds/new',
  path: '/seeds-api/seeds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiSeedsSeedIdRoute = SeedsApiSeedsSeedIdRouteImport.update({
  id: '/seeds-api/seeds/$seedId',
  path: '/seeds-api/seeds/$seedId',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsNewRoute = SeedsApiProjectsNewRouteImport.update({
  id: '/seeds-api/projects/new',
  path: '/seeds-api/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SeedsApiProjectsProjectIdRoute =
  SeedsApiProjectsProjectIdRouteImport.update({
    id: '/seeds-api/projects/$projectId',
    path: '/seeds-api/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ClientsClientIdDataGroupsNewRoute =
  ClientsClientIdDataGroupsNewRouteImport.update({
    id: '/data-groups/new',
    path: '/data-groups/new',
    getParentRoute: () => ClientsClientIdRoute,
  } as any)
const ClientsClientIdDataGroupsDataGroupIdRoute =
  ClientsClientIdDataGroupsDataGroupIdRouteImport.update({
    id: '/data-groups/$dataGroupId',
    path: '/data-groups/$dataGroupId',
    getParentRoute: () => ClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/product/client-skus': typeof ProductClientSkusRoute
  '/region-systems/$regionId': typeof RegionSystemsRegionIdRoute
  '/region-systems/new': typeof RegionSystemsNewRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/retailers/new': typeof RetailersNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/region-systems/': typeof RegionSystemsIndexRoute
  '/retailers/': typeof RetailersIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/seeds/$seedId': typeof SeedsApiSeedsSeedIdRoute
  '/seeds-api/seeds/new': typeof SeedsApiSeedsNewRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
  '/seeds-api/projects/': typeof SeedsApiProjectsIndexRoute
  '/seeds-api/seeds/': typeof SeedsApiSeedsIndexRoute
  '/clients/$clientId/data-groups/$dataGroupId': typeof ClientsClientIdDataGroupsDataGroupIdRoute
  '/clients/$clientId/data-groups/new': typeof ClientsClientIdDataGroupsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/clients/new': typeof ClientsNewRoute
  '/product/client-skus': typeof ProductClientSkusRoute
  '/region-systems/$regionId': typeof RegionSystemsRegionIdRoute
  '/region-systems/new': typeof RegionSystemsNewRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/retailers/new': typeof RetailersNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/clients': typeof ClientsIndexRoute
  '/region-systems': typeof RegionSystemsIndexRoute
  '/retailers': typeof RetailersIndexRoute
  '/stores': typeof StoresIndexRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/seeds/$seedId': typeof SeedsApiSeedsSeedIdRoute
  '/seeds-api/seeds/new': typeof SeedsApiSeedsNewRoute
  '/clients/$clientId': typeof ClientsClientIdIndexRoute
  '/seeds-api/projects': typeof SeedsApiProjectsIndexRoute
  '/seeds-api/seeds': typeof SeedsApiSeedsIndexRoute
  '/clients/$clientId/data-groups/$dataGroupId': typeof ClientsClientIdDataGroupsDataGroupIdRoute
  '/clients/$clientId/data-groups/new': typeof ClientsClientIdDataGroupsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bulk': typeof BulkRoute
  '/data-collector': typeof DataCollectorRoute
  '/iam': typeof IamRoute
  '/clients/$clientId': typeof ClientsClientIdRouteWithChildren
  '/clients/new': typeof ClientsNewRoute
  '/product/client-skus': typeof ProductClientSkusRoute
  '/region-systems/$regionId': typeof RegionSystemsRegionIdRoute
  '/region-systems/new': typeof RegionSystemsNewRoute
  '/retailers/$retailerId': typeof RetailersRetailerIdRoute
  '/retailers/new': typeof RetailersNewRoute
  '/seeds-api/scrapping-options': typeof SeedsApiScrappingOptionsRoute
  '/seeds-api/subscriptions': typeof SeedsApiSubscriptionsRoute
  '/seeds-api/tags': typeof SeedsApiTagsRoute
  '/seeds-api/timeframes': typeof SeedsApiTimeframesRoute
  '/stores/$storeId': typeof StoresStoreIdRoute
  '/stores/new': typeof StoresNewRoute
  '/clients/': typeof ClientsIndexRoute
  '/region-systems/': typeof RegionSystemsIndexRoute
  '/retailers/': typeof RetailersIndexRoute
  '/stores/': typeof StoresIndexRoute
  '/seeds-api/projects/$projectId': typeof SeedsApiProjectsProjectIdRoute
  '/seeds-api/projects/new': typeof SeedsApiProjectsNewRoute
  '/seeds-api/seeds/$seedId': typeof SeedsApiSeedsSeedIdRoute
  '/seeds-api/seeds/new': typeof SeedsApiSeedsNewRoute
  '/clients/$clientId/': typeof ClientsClientIdIndexRoute
  '/seeds-api/projects/': typeof SeedsApiProjectsIndexRoute
  '/seeds-api/seeds/': typeof SeedsApiSeedsIndexRoute
  '/clients/$clientId/data-groups/$dataGroupId': typeof ClientsClientIdDataGroupsDataGroupIdRoute
  '/clients/$clientId/data-groups/new': typeof ClientsClientIdDataGroupsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/clients/$clientId'
    | '/clients/new'
    | '/product/client-skus'
    | '/region-systems/$regionId'
    | '/region-systems/new'
    | '/retailers/$retailerId'
    | '/retailers/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/stores/$storeId'
    | '/stores/new'
    | '/clients/'
    | '/region-systems/'
    | '/retailers/'
    | '/stores/'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/seeds/$seedId'
    | '/seeds-api/seeds/new'
    | '/clients/$clientId/'
    | '/seeds-api/projects/'
    | '/seeds-api/seeds/'
    | '/clients/$clientId/data-groups/$dataGroupId'
    | '/clients/$clientId/data-groups/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/clients/new'
    | '/product/client-skus'
    | '/region-systems/$regionId'
    | '/region-systems/new'
    | '/retailers/$retailerId'
    | '/retailers/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/stores/$storeId'
    | '/stores/new'
    | '/clients'
    | '/region-systems'
    | '/retailers'
    | '/stores'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/seeds/$seedId'
    | '/seeds-api/seeds/new'
    | '/clients/$clientId'
    | '/seeds-api/projects'
    | '/seeds-api/seeds'
    | '/clients/$clientId/data-groups/$dataGroupId'
    | '/clients/$clientId/data-groups/new'
  id:
    | '__root__'
    | '/'
    | '/bulk'
    | '/data-collector'
    | '/iam'
    | '/clients/$clientId'
    | '/clients/new'
    | '/product/client-skus'
    | '/region-systems/$regionId'
    | '/region-systems/new'
    | '/retailers/$retailerId'
    | '/retailers/new'
    | '/seeds-api/scrapping-options'
    | '/seeds-api/subscriptions'
    | '/seeds-api/tags'
    | '/seeds-api/timeframes'
    | '/stores/$storeId'
    | '/stores/new'
    | '/clients/'
    | '/region-systems/'
    | '/retailers/'
    | '/stores/'
    | '/seeds-api/projects/$projectId'
    | '/seeds-api/projects/new'
    | '/seeds-api/seeds/$seedId'
    | '/seeds-api/seeds/new'
    | '/clients/$clientId/'
    | '/seeds-api/projects/'
    | '/seeds-api/seeds/'
    | '/clients/$clientId/data-groups/$dataGroupId'
    | '/clients/$clientId/data-groups/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BulkRoute: typeof BulkRoute
  DataCollectorRoute: typeof DataCollectorRoute
  IamRoute: typeof IamRoute
  ClientsClientIdRoute: typeof ClientsClientIdRouteWithChildren
  ClientsNewRoute: typeof ClientsNewRoute
  ProductClientSkusRoute: typeof ProductClientSkusRoute
  RegionSystemsRegionIdRoute: typeof RegionSystemsRegionIdRoute
  RegionSystemsNewRoute: typeof RegionSystemsNewRoute
  RetailersRetailerIdRoute: typeof RetailersRetailerIdRoute
  RetailersNewRoute: typeof RetailersNewRoute
  SeedsApiScrappingOptionsRoute: typeof SeedsApiScrappingOptionsRoute
  SeedsApiSubscriptionsRoute: typeof SeedsApiSubscriptionsRoute
  SeedsApiTagsRoute: typeof SeedsApiTagsRoute
  SeedsApiTimeframesRoute: typeof SeedsApiTimeframesRoute
  StoresStoreIdRoute: typeof StoresStoreIdRoute
  StoresNewRoute: typeof StoresNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  RegionSystemsIndexRoute: typeof RegionSystemsIndexRoute
  RetailersIndexRoute: typeof RetailersIndexRoute
  StoresIndexRoute: typeof StoresIndexRoute
  SeedsApiProjectsProjectIdRoute: typeof SeedsApiProjectsProjectIdRoute
  SeedsApiProjectsNewRoute: typeof SeedsApiProjectsNewRoute
  SeedsApiSeedsSeedIdRoute: typeof SeedsApiSeedsSeedIdRoute
  SeedsApiSeedsNewRoute: typeof SeedsApiSeedsNewRoute
  SeedsApiProjectsIndexRoute: typeof SeedsApiProjectsIndexRoute
  SeedsApiSeedsIndexRoute: typeof SeedsApiSeedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/iam': {
      id: '/iam'
      path: '/iam'
      fullPath: '/iam'
      preLoaderRoute: typeof IamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-collector': {
      id: '/data-collector'
      path: '/data-collector'
      fullPath: '/data-collector'
      preLoaderRoute: typeof DataCollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bulk': {
      id: '/bulk'
      path: '/bulk'
      fullPath: '/bulk'
      preLoaderRoute: typeof BulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/': {
      id: '/stores/'
      path: '/stores'
      fullPath: '/stores/'
      preLoaderRoute: typeof StoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/': {
      id: '/retailers/'
      path: '/retailers'
      fullPath: '/retailers/'
      preLoaderRoute: typeof RetailersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region-systems/': {
      id: '/region-systems/'
      path: '/region-systems'
      fullPath: '/region-systems/'
      preLoaderRoute: typeof RegionSystemsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/new': {
      id: '/stores/new'
      path: '/stores/new'
      fullPath: '/stores/new'
      preLoaderRoute: typeof StoresNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores/$storeId': {
      id: '/stores/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/timeframes': {
      id: '/seeds-api/timeframes'
      path: '/seeds-api/timeframes'
      fullPath: '/seeds-api/timeframes'
      preLoaderRoute: typeof SeedsApiTimeframesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/tags': {
      id: '/seeds-api/tags'
      path: '/seeds-api/tags'
      fullPath: '/seeds-api/tags'
      preLoaderRoute: typeof SeedsApiTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/subscriptions': {
      id: '/seeds-api/subscriptions'
      path: '/seeds-api/subscriptions'
      fullPath: '/seeds-api/subscriptions'
      preLoaderRoute: typeof SeedsApiSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/scrapping-options': {
      id: '/seeds-api/scrapping-options'
      path: '/seeds-api/scrapping-options'
      fullPath: '/seeds-api/scrapping-options'
      preLoaderRoute: typeof SeedsApiScrappingOptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/new': {
      id: '/retailers/new'
      path: '/retailers/new'
      fullPath: '/retailers/new'
      preLoaderRoute: typeof RetailersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailers/$retailerId': {
      id: '/retailers/$retailerId'
      path: '/retailers/$retailerId'
      fullPath: '/retailers/$retailerId'
      preLoaderRoute: typeof RetailersRetailerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region-systems/new': {
      id: '/region-systems/new'
      path: '/region-systems/new'
      fullPath: '/region-systems/new'
      preLoaderRoute: typeof RegionSystemsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/region-systems/$regionId': {
      id: '/region-systems/$regionId'
      path: '/region-systems/$regionId'
      fullPath: '/region-systems/$regionId'
      preLoaderRoute: typeof RegionSystemsRegionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/client-skus': {
      id: '/product/client-skus'
      path: '/product/client-skus'
      fullPath: '/product/client-skus'
      preLoaderRoute: typeof ProductClientSkusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/seeds/': {
      id: '/seeds-api/seeds/'
      path: '/seeds-api/seeds'
      fullPath: '/seeds-api/seeds/'
      preLoaderRoute: typeof SeedsApiSeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/': {
      id: '/seeds-api/projects/'
      path: '/seeds-api/projects'
      fullPath: '/seeds-api/projects/'
      preLoaderRoute: typeof SeedsApiProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/': {
      id: '/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof ClientsClientIdIndexRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/seeds-api/seeds/new': {
      id: '/seeds-api/seeds/new'
      path: '/seeds-api/seeds/new'
      fullPath: '/seeds-api/seeds/new'
      preLoaderRoute: typeof SeedsApiSeedsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/seeds/$seedId': {
      id: '/seeds-api/seeds/$seedId'
      path: '/seeds-api/seeds/$seedId'
      fullPath: '/seeds-api/seeds/$seedId'
      preLoaderRoute: typeof SeedsApiSeedsSeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/new': {
      id: '/seeds-api/projects/new'
      path: '/seeds-api/projects/new'
      fullPath: '/seeds-api/projects/new'
      preLoaderRoute: typeof SeedsApiProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seeds-api/projects/$projectId': {
      id: '/seeds-api/projects/$projectId'
      path: '/seeds-api/projects/$projectId'
      fullPath: '/seeds-api/projects/$projectId'
      preLoaderRoute: typeof SeedsApiProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId/data-groups/new': {
      id: '/clients/$clientId/data-groups/new'
      path: '/data-groups/new'
      fullPath: '/clients/$clientId/data-groups/new'
      preLoaderRoute: typeof ClientsClientIdDataGroupsNewRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
    '/clients/$clientId/data-groups/$dataGroupId': {
      id: '/clients/$clientId/data-groups/$dataGroupId'
      path: '/data-groups/$dataGroupId'
      fullPath: '/clients/$clientId/data-groups/$dataGroupId'
      preLoaderRoute: typeof ClientsClientIdDataGroupsDataGroupIdRouteImport
      parentRoute: typeof ClientsClientIdRoute
    }
  }
}

interface ClientsClientIdRouteChildren {
  ClientsClientIdIndexRoute: typeof ClientsClientIdIndexRoute
  ClientsClientIdDataGroupsDataGroupIdRoute: typeof ClientsClientIdDataGroupsDataGroupIdRoute
  ClientsClientIdDataGroupsNewRoute: typeof ClientsClientIdDataGroupsNewRoute
}

const ClientsClientIdRouteChildren: ClientsClientIdRouteChildren = {
  ClientsClientIdIndexRoute: ClientsClientIdIndexRoute,
  ClientsClientIdDataGroupsDataGroupIdRoute:
    ClientsClientIdDataGroupsDataGroupIdRoute,
  ClientsClientIdDataGroupsNewRoute: ClientsClientIdDataGroupsNewRoute,
}

const ClientsClientIdRouteWithChildren = ClientsClientIdRoute._addFileChildren(
  ClientsClientIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BulkRoute: BulkRoute,
  DataCollectorRoute: DataCollectorRoute,
  IamRoute: IamRoute,
  ClientsClientIdRoute: ClientsClientIdRouteWithChildren,
  ClientsNewRoute: ClientsNewRoute,
  ProductClientSkusRoute: ProductClientSkusRoute,
  RegionSystemsRegionIdRoute: RegionSystemsRegionIdRoute,
  RegionSystemsNewRoute: RegionSystemsNewRoute,
  RetailersRetailerIdRoute: RetailersRetailerIdRoute,
  RetailersNewRoute: RetailersNewRoute,
  SeedsApiScrappingOptionsRoute: SeedsApiScrappingOptionsRoute,
  SeedsApiSubscriptionsRoute: SeedsApiSubscriptionsRoute,
  SeedsApiTagsRoute: SeedsApiTagsRoute,
  SeedsApiTimeframesRoute: SeedsApiTimeframesRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  StoresNewRoute: StoresNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  RegionSystemsIndexRoute: RegionSystemsIndexRoute,
  RetailersIndexRoute: RetailersIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
  SeedsApiProjectsProjectIdRoute: SeedsApiProjectsProjectIdRoute,
  SeedsApiProjectsNewRoute: SeedsApiProjectsNewRoute,
  SeedsApiSeedsSeedIdRoute: SeedsApiSeedsSeedIdRoute,
  SeedsApiSeedsNewRoute: SeedsApiSeedsNewRoute,
  SeedsApiProjectsIndexRoute: SeedsApiProjectsIndexRoute,
  SeedsApiSeedsIndexRoute: SeedsApiSeedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
